// French Quiz Data
const frenchQuizData = {
    A1: [
        { word: "Maison", options: ["House", "Car", "Dog", "Tree"], correct: "House" },
    { word: "Chat", options: ["Cat", "Bird", "Horse", "Mouse"], correct: "Cat" },
    { word: "Voiture", options: ["Car", "Bus", "Train", "Bicycle"], correct: "Car" },
    { word: "Chien", options: ["Dog", "Cat", "Fish", "Bird"], correct: "Dog" },
    { word: "Arbre", options: ["Tree", "Flower", "Plant", "Bush"], correct: "Tree" },
    { word: "Fleur", options: ["Flower", "Tree", "Bush", "Plant"], correct: "Flower" },
    { word: "Livre", options: ["Book", "Pen", "Notebook", "Paper"], correct: "Book" },
    { word: "Table", options: ["Table", "Chair", "Sofa", "Desk"], correct: "Table" },
    { word: "Chaise", options: ["Chair", "Table", "Sofa", "Bed"], correct: "Chair" },
    { word: "Ciel", options: ["Sky", "Ocean", "Earth", "Moon"], correct: "Sky" },
    { word: "Soleil", options: ["Sun", "Moon", "Star", "Cloud"], correct: "Sun" },
    { word: "Lune", options: ["Moon", "Sun", "Cloud", "Star"], correct: "Moon" },
    { word: "Eau", options: ["Water", "Milk", "Juice", "Tea"], correct: "Water" },
    { word: "Pain", options: ["Bread", "Rice", "Potato", "Pasta"], correct: "Bread" },
    { word: "Fromage", options: ["Cheese", "Meat", "Fruit", "Vegetable"], correct: "Cheese" },
    { word: "Fruit", options: ["Fruit", "Vegetable", "Bread", "Meat"], correct: "Fruit" },
    { word: "Légume", options: ["Vegetable", "Fruit", "Bread", "Meat"], correct: "Vegetable" },
    { word: "Poisson", options: ["Fish", "Meat", "Bread", "Vegetable"], correct: "Fish" },
    { word: "Viande", options: ["Meat", "Fish", "Fruit", "Vegetable"], correct: "Meat" },
    { word: "Voix", options: ["Voice", "Ear", "Eye", "Mouth"], correct: "Voice" },
    { word: "Main", options: ["Hand", "Foot", "Leg", "Arm"], correct: "Hand" },
    { word: "Pied", options: ["Foot", "Hand", "Arm", "Leg"], correct: "Foot" },
    { word: "Bouche", options: ["Mouth", "Nose", "Ear", "Eye"], correct: "Mouth" },
    { word: "Oreille", options: ["Ear", "Eye", "Mouth", "Nose"], correct: "Ear" },
    { word: "Œil", options: ["Eye", "Ear", "Mouth", "Nose"], correct: "Eye" },
    { word: "Nez", options: ["Nose", "Ear", "Mouth", "Eye"], correct: "Nose" },
    { word: "Cheveux", options: ["Hair", "Teeth", "Eyes", "Hands"], correct: "Hair" },
    { word: "Dent", options: ["Tooth", "Tongue", "Ear", "Mouth"], correct: "Tooth" },
    { word: "Tête", options: ["Head", "Hand", "Foot", "Leg"], correct: "Head" },
    { word: "Corps", options: ["Body", "Arm", "Leg", "Foot"], correct: "Body" },
    { word: "Amis", options: ["Friends", "Family", "Neighbors", "Colleagues"], correct: "Friends" },
    { word: "Famille", options: ["Family", "Friends", "Neighbors", "Classmates"], correct: "Family" },
    { word: "École", options: ["School", "Library", "Park", "Hospital"], correct: "School" },
    { word: "Université", options: ["University", "School", "Library", "College"], correct: "University" },
    { word: "Travail", options: ["Work", "Study", "Play", "Eat"], correct: "Work" },
    { word: "Manger", options: ["Eat", "Sleep", "Drink", "Walk"], correct: "Eat" },
    { word: "Boire", options: ["Drink", "Eat", "Sleep", "Run"], correct: "Drink" },
    { word: "Marcher", options: ["Walk", "Run", "Jump", "Climb"], correct: "Walk" },
    { word: "Courir", options: ["Run", "Walk", "Sleep", "Jump"], correct: "Run" },
    { word: "Dormir", options: ["Sleep", "Eat", "Work", "Run"], correct: "Sleep" },
    { word: "Vêtements", options: ["Clothes", "Shoes", "Bags", "Glasses"], correct: "Clothes" },
    { word: "Chaussures", options: ["Shoes", "Bags", "Clothes", "Socks"], correct: "Shoes" },
    { word: "Sac", options: ["Bag", "Shoe", "Hat", "Jacket"], correct: "Bag" },
    { word: "Chapeau", options: ["Hat", "Gloves", "Scarf", "Socks"], correct: "Hat" },
    { word: "Pantalon", options: ["Pants", "Shirt", "Shoes", "Hat"], correct: "Pants" },
    { word: "Chemise", options: ["Shirt", "Pants", "Socks", "Shoes"], correct: "Shirt" },
    { word: "Jupe", options: ["Skirt", "Pants", "Shirt", "Sweater"], correct: "Skirt" },
    { word: "Robe", options: ["Dress", "Shirt", "Skirt", "Pants"], correct: "Dress" },
    { word: "Chaud", options: ["Hot", "Cold", "Warm", "Cool"], correct: "Hot" },
    { word: "Froid", options: ["Cold", "Hot", "Warm", "Cool"], correct: "Cold" },
    { word: "Soleil", options: ["Sun", "Moon", "Cloud", "Star"], correct: "Sun" },
    { word: "Pluie", options: ["Rain", "Snow", "Wind", "Cloud"], correct: "Rain" },
    { word: "Neige", options: ["Snow", "Rain", "Wind", "Cloud"], correct: "Snow" },
    { word: "Vent", options: ["Wind", "Rain", "Snow", "Cloud"], correct: "Wind" },
    { word: "Chaud", options: ["Warm", "Hot", "Cold", "Cool"], correct: "Warm" },
    { word: "Hiver", options: ["Winter", "Spring", "Summer", "Autumn"], correct: "Winter" },
    { word: "Été", options: ["Summer", "Winter", "Spring", "Autumn"], correct: "Summer" },
    { word: "Automne", options: ["Autumn", "Winter", "Spring", "Summer"], correct: "Autumn" },
    { word: "Printemps", options: ["Spring", "Winter", "Summer", "Autumn"], correct: "Spring" },{ word: "Maison", options: ["House", "Tree", "Car", "Dog"], correct: "House" },
    { word: "Chat", options: ["Horse", "Cat", "Bird", "Mouse"], correct: "Cat" },
    { word: "Voiture", options: ["Bicycle", "Car", "Bus", "Train"], correct: "Car" },
    { word: "Chien", options: ["Fish", "Bird", "Dog", "Cat"], correct: "Dog" },
    { word: "Arbre", options: ["Tree", "Flower", "Plant", "Bush"], correct: "Tree" },
    { word: "Fleur", options: ["Flower", "Bush", "Plant", "Tree"], correct: "Flower" },
    { word: "Livre", options: ["Pen", "Notebook", "Book", "Paper"], correct: "Book" },
    { word: "Table", options: ["Desk", "Sofa", "Table", "Chair"], correct: "Table" },
    { word: "Chaise", options: ["Chair", "Table", "Bed", "Sofa"], correct: "Chair" },
    { word: "Ciel", options: ["Ocean", "Earth", "Moon", "Sky"], correct: "Sky" },
    { word: "Soleil", options: ["Sun", "Moon", "Cloud", "Star"], correct: "Sun" },
    { word: "Lune", options: ["Moon", "Star", "Sun", "Cloud"], correct: "Moon" },
    { word: "Eau", options: ["Milk", "Tea", "Water", "Juice"], correct: "Water" },
    { word: "Pain", options: ["Rice", "Potato", "Bread", "Pasta"], correct: "Bread" },
    { word: "Fromage", options: ["Fruit", "Cheese", "Vegetable", "Meat"], correct: "Cheese" },
    { word: "Fruit", options: ["Vegetable", "Bread", "Fruit", "Meat"], correct: "Fruit" },
    { word: "Légume", options: ["Meat", "Vegetable", "Fruit", "Bread"], correct: "Vegetable" },
    { word: "Poisson", options: ["Vegetable", "Fish", "Meat", "Bread"], correct: "Fish" },
    { word: "Viande", options: ["Fish", "Meat", "Fruit", "Vegetable"], correct: "Meat" },
    { word: "Voix", options: ["Mouth", "Ear", "Eye", "Voice"], correct: "Voice" },
    { word: "Main", options: ["Foot", "Hand", "Leg", "Arm"], correct: "Hand" },
    { word: "Pied", options: ["Foot", "Leg", "Hand", "Arm"], correct: "Foot" },
    { word: "Bouche", options: ["Nose", "Ear", "Mouth", "Eye"], correct: "Mouth" },
    { word: "Oreille", options: ["Eye", "Mouth", "Ear", "Nose"], correct: "Ear" },
    { word: "Œil", options: ["Eye", "Nose", "Mouth", "Ear"], correct: "Eye" },
    { word: "Nez", options: ["Ear", "Eye", "Mouth", "Nose"], correct: "Nose" },
    { word: "Cheveux", options: ["Eyes", "Teeth", "Hair", "Hands"], correct: "Hair" },
    { word: "Dent", options: ["Tongue", "Tooth", "Ear", "Mouth"], correct: "Tooth" },
    { word: "Tête", options: ["Head", "Foot", "Hand", "Leg"], correct: "Head" },
    { word: "Corps", options: ["Foot", "Body", "Arm", "Leg"], correct: "Body" },
    { word: "Amis", options: ["Classmates", "Neighbors", "Family", "Friends"], correct: "Friends" },
    { word: "Famille", options: ["Friends", "Family", "Neighbors", "Classmates"], correct: "Family" },
    { word: "École", options: ["School", "Park", "Hospital", "Library"], correct: "School" },
    { word: "Université", options: ["School", "College", "University", "Library"], correct: "University" },
    { word: "Travail", options: ["Play", "Eat", "Work", "Study"], correct: "Work" },
    { word: "Manger", options: ["Work", "Eat", "Sleep", "Drink"], correct: "Eat" },
    { word: "Boire", options: ["Sleep", "Run", "Drink", "Eat"], correct: "Drink" },
    { word: "Marcher", options: ["Run", "Jump", "Walk", "Climb"], correct: "Walk" },
    { word: "Courir", options: ["Jump", "Run", "Walk", "Climb"], correct: "Run" },
    { word: "Dormir", options: ["Drink", "Eat", "Sleep", "Work"], correct: "Sleep" },
    { word: "Vêtements", options: ["Bags", "Glasses", "Clothes", "Shoes"], correct: "Clothes" },
    { word: "Chaussures", options: ["Bags", "Shoes", "Clothes", "Socks"], correct: "Shoes" },
    { word: "Sac", options: ["Shoe", "Bag", "Jacket", "Hat"], correct: "Bag" },
    { word: "Chapeau", options: ["Socks", "Gloves", "Hat", "Scarf"], correct: "Hat" },
    { word: "Pantalon", options: ["Shirt", "Pants", "Hat", "Shoes"], correct: "Pants" },
    { word: "Chemise", options: ["Shirt", "Shoes", "Socks", "Pants"], correct: "Shirt" },
    { word: "Jupe", options: ["Shirt", "Skirt", "Sweater", "Pants"], correct: "Skirt" },
    { word: "Robe", options: ["Skirt", "Pants", "Dress", "Shirt"], correct: "Dress" },
    { word: "Chaud", options: ["Hot", "Cold", "Cool", "Warm"], correct: "Hot" },
    { word: "Froid", options: ["Cold", "Warm", "Cool", "Hot"], correct: "Cold" },
    { word: "Soleil", options: ["Star", "Cloud", "Sun", "Moon"], correct: "Sun" },
    { word: "Pluie", options: ["Rain", "Wind", "Cloud", "Snow"], correct: "Rain" },
    { word: "Neige", options: ["Cloud", "Wind", "Snow", "Rain"], correct: "Snow" },
    { word: "Vent", options: ["Wind", "Rain", "Snow", "Cloud"], correct: "Wind" },
    { word: "Chaud", options: ["Cool", "Cold", "Warm", "Hot"], correct: "Warm" },
    { word: "Hiver", options: ["Autumn", "Winter", "Summer", "Spring"], correct: "Winter" },
    { word: "Été", options: ["Summer", "Autumn", "Winter", "Spring"], correct: "Summer" },
    { word: "Automne", options: ["Autumn", "Summer", "Spring", "Winter"], correct: "Autumn" },
    { word: "Printemps", options: ["Spring", "Winter", "Summer", "Autumn"], correct: "Spring" }
    ],
    A2: [
        { word: "Payer", options: ["Eat", "Buy", "Pay", "Sell"], correct: "Pay" },
    { word: "Savoir", options: ["Know", "Go", "See", "Come"], correct: "Know" },
    { word: "Vouloir", options: ["Want", "Do", "Have", "Be"], correct: "Want" },
    { word: "Finir", options: ["Start", "Finish", "Pause", "Work"], correct: "Finish" },
    { word: "Lire", options: ["Read", "Write", "Speak", "Listen"], correct: "Read" },
    { word: "Écrire", options: ["Speak", "Read", "Write", "Listen"], correct: "Write" },
    { word: "Manger", options: ["Drink", "Sleep", "Eat", "Work"], correct: "Eat" },
    { word: "Marcher", options: ["Run", "Walk", "Dance", "Jump"], correct: "Walk" },
    { word: "Parler", options: ["Talk", "Sleep", "Walk", "Eat"], correct: "Talk" },
    { word: "Regarder", options: ["Listen", "Look", "Jump", "Run"], correct: "Look" },
    { word: "Entendre", options: ["Hear", "See", "Speak", "Write"], correct: "Hear" },
    { word: "Voir", options: ["Look", "See", "Talk", "Read"], correct: "See" },
    { word: "Dormir", options: ["Eat", "Sleep", "Work", "Sing"], correct: "Sleep" },
    { word: "Vendre", options: ["Buy", "Sell", "Drink", "Write"], correct: "Sell" },
    { word: "Acheter", options: ["Buy", "Sell", "Work", "Play"], correct: "Buy" },
    { word: "Attendre", options: ["Wait", "Listen", "Run", "Talk"], correct: "Wait" },
    { word: "Répondre", options: ["Ask", "Answer", "Listen", "Work"], correct: "Answer" },
    { word: "Chercher", options: ["Find", "Look", "Search", "Read"], correct: "Search" },
    { word: "Trouver", options: ["Search", "Find", "Look", "Watch"], correct: "Find" },
    { word: "Comprendre", options: ["Understand", "Talk", "Read", "Write"], correct: "Understand" },
    { word: "Apprendre", options: ["Teach", "Learn", "Work", "Study"], correct: "Learn" },
    { word: "Donner", options: ["Give", "Take", "Buy", "Sell"], correct: "Give" },
    { word: "Recevoir", options: ["Give", "Take", "Receive", "Send"], correct: "Receive" },
    { word: "Penser", options: ["Think", "Write", "Sleep", "Work"], correct: "Think" },
    { word: "Rire", options: ["Cry", "Laugh", "Talk", "Eat"], correct: "Laugh" },
    { word: "Aimer", options: ["Like", "Hate", "Sleep", "Work"], correct: "Like" },
    { word: "Délier", options: ["Tie", "Untie", "Work", "Eat"], correct: "Untie" },
    { word: "Aider", options: ["Help", "Teach", "Listen", "Talk"], correct: "Help" },
    { word: "Cuisiner", options: ["Cook", "Eat", "Sleep", "Run"], correct: "Cook" },
    { word: "Visiter", options: ["Look", "Visit", "Walk", "Stay"], correct: "Visit" },
    { word: "Explorer", options: ["Find", "Explore", "Look", "Read"], correct: "Explore" },
    { word: "Changer", options: ["Change", "Stay", "Talk", "Sit"], correct: "Change" },
    { word: "Montrer", options: ["Show", "See", "Talk", "Wait"], correct: "Show" },
    { word: "Fermer", options: ["Open", "Close", "Talk", "Eat"], correct: "Close" },
    { word: "Ouvrir", options: ["Close", "Open", "Talk", "Wait"], correct: "Open" },
    { word: "Commencer", options: ["End", "Start", "Talk", "Write"], correct: "Start" },
    { word: "Finir", options: ["Finish", "Start", "Talk", "Look"], correct: "Finish" },
    { word: "Sentir", options: ["Feel", "Touch", "Look", "Talk"], correct: "Feel" },
    { word: "Porter", options: ["Wear", "Hold", "Give", "Take"], correct: "Wear" },
    { word: "Essayer", options: ["Try", "Give", "Wait", "Listen"], correct: "Try" },
    { word: "Avoir", options: ["Be", "Have", "Do", "Make"], correct: "Have" },
    { word: "Être", options: ["Do", "Have", "Be", "Make"], correct: "Be" },
    { word: "Faire", options: ["Do", "Make", "Have", "Be"], correct: "Do" },
    { word: "Aller", options: ["Go", "Stay", "Leave", "Wait"], correct: "Go" },
    { word: "Venir", options: ["Go", "Come", "Leave", "Stay"], correct: "Come" },
    { word: "S'asseoir", options: ["Sit", "Stand", "Wait", "Leave"], correct: "Sit" },
    { word: "Se lever", options: ["Sit", "Stand", "Walk", "Jump"], correct: "Stand" },
    { word: "Rentrer", options: ["Enter", "Leave", "Stay", "Come"], correct: "Enter" },
    { word: "Partir", options: ["Go", "Leave", "Stay", "Come"], correct: "Leave" },
    { word: "Nager", options: ["Swim", "Run", "Jump", "Fly"], correct: "Swim" },
    { word: "Voler", options: ["Fly", "Walk", "Run", "Jump"], correct: "Fly" },
    { word: "Connaître", options: ["Know", "Meet", "See", "Look"], correct: "Know" },
    { word: "Croire", options: ["Think", "Believe", "Say", "Look"], correct: "Believe" },
    { word: "Trouver", options: ["Look", "Search", "Find", "Give"], correct: "Find" },
    { word: "Accepter", options: ["Give", "Take", "Accept", "Reject"], correct: "Accept" },
    { word: "Refuser", options: ["Reject", "Accept", "Give", "Take"], correct: "Reject" },
    { word: "Recevoir", options: ["Give", "Take", "Receive", "Send"], correct: "Receive" },
    { word: "Prendre", options: ["Take", "Give", "Sell", "Buy"], correct: "Take" },
    { word: "Boire", options: ["Eat", "Drink", "Work", "Talk"], correct: "Drink" },
    { word: "Rentrer", options: ["Enter", "Leave", "Stay", "Go"], correct: "Enter" },
    { word: "Jouer", options: ["Read", "Talk", "Work", "Play"], correct: "Play" },
    { word: "Travailler", options: ["Talk", "Work", "Read", "Write"], correct: "Work" }
    ],
    B1: [
        { word: "Réussir", options: ["Fail", "Succeed", "Listen", "Talk"], correct: "Succeed" },
    { word: "Gérer", options: ["Manage", "Ignore", "Speak", "Understand"], correct: "Manage" },
    { word: "Accepter", options: ["Reject", "Accept", "Give", "Take"], correct: "Accept" },
    { word: "Décrire", options: ["Describe", "Understand", "Speak", "Read"], correct: "Describe" },
    { word: "Attirer", options: ["Push", "Pull", "Attract", "Repel"], correct: "Attract" },
    { word: "Vivre", options: ["Live", "Die", "Talk", "Work"], correct: "Live" },
    { word: "Construire", options: ["Destroy", "Build", "Talk", "Sing"], correct: "Build" },
    { word: "Soutenir", options: ["Support", "Ignore", "Criticize", "Talk"], correct: "Support" },
    { word: "Partager", options: ["Share", "Hide", "Keep", "Take"], correct: "Share" },
    { word: "Exprimer", options: ["Express", "Keep", "Hide", "Say"], correct: "Express" },
    { word: "Résoudre", options: ["Solve", "Avoid", "Talk", "Listen"], correct: "Solve" },
    { word: "Réfléchir", options: ["Think", "Talk", "Laugh", "Walk"], correct: "Think" },
    { word: "Améliorer", options: ["Improve", "Destroy", "Ignore", "Take"], correct: "Improve" },
    { word: "Compliquer", options: ["Simplify", "Complicate", "Improve", "Talk"], correct: "Complicate" },
    { word: "Perdre", options: ["Win", "Lose", "Talk", "Speak"], correct: "Lose" },
    { word: "Assumer", options: ["Hide", "Accept", "Avoid", "Talk"], correct: "Accept" },
    { word: "Cacher", options: ["Hide", "Show", "Talk", "Understand"], correct: "Hide" },
    { word: "Connaître", options: ["Know", "See", "Speak", "Look"], correct: "Know" },
    { word: "Avoir", options: ["Have", "Be", "Do", "Make"], correct: "Have" },
    { word: "Pardonner", options: ["Forgive", "Blame", "Judge", "Talk"], correct: "Forgive" },
    { word: "Rejoindre", options: ["Join", "Leave", "Stay", "Talk"], correct: "Join" },
    { word: "Douter", options: ["Believe", "Doubt", "Think", "Speak"], correct: "Doubt" },
    { word: "Obtenir", options: ["Lose", "Get", "Take", "Speak"], correct: "Get" },
    { word: "Crier", options: ["Whisper", "Shout", "Talk", "Laugh"], correct: "Shout" },
    { word: "Changer", options: ["Change", "Stay", "Look", "Jump"], correct: "Change" },
    { word: "Comprendre", options: ["Misunderstand", "Understand", "Talk", "Look"], correct: "Understand" },
    { word: "Préparer", options: ["Prepare", "Talk", "Sing", "Work"], correct: "Prepare" },
    { word: "Éviter", options: ["Avoid", "Do", "Talk", "Look"], correct: "Avoid" },
    { word: "Se concentrer", options: ["Focus", "Sleep", "Talk", "Rest"], correct: "Focus" },
    { word: "Fournir", options: ["Give", "Take", "Leave", "Talk"], correct: "Give" },
    { word: "Disparaître", options: ["Disappear", "Appear", "Stay", "Look"], correct: "Disappear" },
    { word: "S'échapper", options: ["Escape", "Enter", "Stay", "Leave"], correct: "Escape" },
    { word: "Déterminer", options: ["Decide", "Ignore", "Talk", "Work"], correct: "Decide" },
    { word: "Lancer", options: ["Catch", "Throw", "Talk", "Run"], correct: "Throw" },
    { word: "Protéger", options: ["Attack", "Protect", "Criticize", "Hurt"], correct: "Protect" },
    { word: "Renvoyer", options: ["Send", "Return", "Leave", "Bring"], correct: "Return" },
    { word: "Prendre", options: ["Give", "Take", "See", "Talk"], correct: "Take" },
    { word: "Saisir", options: ["Grab", "Look", "Hold", "Talk"], correct: "Grab" },
    { word: "Développer", options: ["Develop", "Stop", "Look", "Talk"], correct: "Develop" },
    { word: "Attendre", options: ["Wait", "Run", "Go", "Talk"], correct: "Wait" },
    { word: "Respecter", options: ["Disrespect", "Respect", "Ignore", "Hurt"], correct: "Respect" },
    { word: "Suivre", options: ["Lead", "Follow", "Stop", "Talk"], correct: "Follow" },
    { word: "Accomplir", options: ["Finish", "Start", "Do", "Pause"], correct: "Finish" },
    { word: "Trouver", options: ["Look", "Search", "Find", "Give"], correct: "Find" },
    { word: "Rencontrer", options: ["Meet", "Leave", "Talk", "Look"], correct: "Meet" },
    { word: "Construire", options: ["Build", "Destroy", "Look", "Talk"], correct: "Build" },
    { word: "Fuir", options: ["Stay", "Run", "Jump", "Wait"], correct: "Run" },
    { word: "Répondre", options: ["Answer", "Ask", "Talk", "Look"], correct: "Answer" },
    { word: "Servir", options: ["Serve", "Take", "Give", "Talk"], correct: "Serve" },
    { word: "Essayer", options: ["Avoid", "Try", "Do", "Talk"], correct: "Try" },
    { word: "Rappeler", options: ["Remember", "Forget", "Talk", "Look"], correct: "Remember" },
    { word: "Observer", options: ["Look", "Talk", "Work", "Wait"], correct: "Look" },
    { word: "Perdre", options: ["Win", "Lose", "Find", "Stay"], correct: "Lose" },
    { word: "Participer", options: ["Join", "Avoid", "Look", "Give"], correct: "Join" },
    { word: "Fixer", options: ["Break", "Set", "Look", "Talk"], correct: "Set" },
    { word: "Interdire", options: ["Allow", "Prohibit", "Speak", "Look"], correct: "Prohibit" },
    { word: "Quitter", options: ["Stay", "Leave", "Talk", "Look"], correct: "Leave" },
    { word: "Attirer", options: ["Repel", "Attract", "Push", "Speak"], correct: "Attract" },
    { word: "Percevoir", options: ["Hear", "See", "Talk", "Feel"], correct: "See" },
    { word: "Obliger", options: ["Force", "Allow", "Talk", "Look"], correct: "Force" },
    { word: "Acquérir", options: ["Lose", "Get", "Leave", "Talk"], correct: "Get" },
    { word: "Éviter", options: ["Do", "Avoid", "Talk", "Look"], correct: "Avoid" },
    { word: "Douter", options: ["Believe", "Doubt", "Talk", "Look"], correct: "Doubt" },{ word: "Réussir", options: ["Fail", "Succeed", "Walk", "Talk"], correct: "Succeed" },
    { word: "Plonger", options: ["Dive", "Fly", "Walk", "Sleep"], correct: "Dive" },
    { word: "Obtenir", options: ["Lose", "Get", "Give", "Take"], correct: "Get" },
    { word: "Compter", options: ["Count", "Talk", "Look", "Write"], correct: "Count" },
    { word: "Cuisiner", options: ["Cook", "Talk", "Listen", "Run"], correct: "Cook" },
    { word: "Choisir", options: ["Choose", "Reject", "Decide", "Look"], correct: "Choose" },
    { word: "Écouter", options: ["Hear", "Look", "Speak", "Listen"], correct: "Listen" },
    { word: "Vivre", options: ["Die", "Live", "Walk", "Talk"], correct: "Live" },
    { word: "Jouer", options: ["Play", "Sleep", "Talk", "Sing"], correct: "Play" },
    { word: "Lancer", options: ["Catch", "Throw", "Take", "Jump"], correct: "Throw" },
    { word: "Travailler", options: ["Work", "Rest", "Talk", "Look"], correct: "Work" },
    { word: "Prendre", options: ["Give", "Take", "Look", "Stop"], correct: "Take" },
    { word: "Répéter", options: ["Repeat", "Say", "Think", "Understand"], correct: "Repeat" },
    { word: "Répondre", options: ["Ask", "Answer", "Speak", "Think"], correct: "Answer" },
    { word: "Dîner", options: ["Eat", "Talk", "Sleep", "Walk"], correct: "Eat" },
    { word: "Aider", options: ["Help", "Hurt", "Talk", "Think"], correct: "Help" },
    { word: "Chanter", options: ["Sing", "Dance", "Talk", "Jump"], correct: "Sing" },
    { word: "Chercher", options: ["Search", "Find", "See", "Talk"], correct: "Search" },
    { word: "Apprendre", options: ["Learn", "Teach", "Talk", "Forget"], correct: "Learn" },
    { word: "Demander", options: ["Ask", "Answer", "Speak", "Think"], correct: "Ask" },
    { word: "Réfléchir", options: ["Think", "Talk", "Look", "Walk"], correct: "Think" },
    { word: "Attendre", options: ["Wait", "Run", "Jump", "Look"], correct: "Wait" },
    { word: "Oublier", options: ["Forget", "Remember", "Talk", "Look"], correct: "Forget" },
    { word: "Acheter", options: ["Sell", "Buy", "Give", "Look"], correct: "Buy" },
    { word: "Rencontrer", options: ["Meet", "Leave", "Talk", "Sleep"], correct: "Meet" },
    { word: "Commencer", options: ["Start", "Finish", "Talk", "Look"], correct: "Start" },
    { word: "Finir", options: ["Finish", "Start", "Look", "Wait"], correct: "Finish" },
    { word: "Gagner", options: ["Win", "Lose", "Talk", "Look"], correct: "Win" },
    { word: "Perdre", options: ["Lose", "Win", "Talk", "Look"], correct: "Lose" },
    { word: "Partager", options: ["Share", "Keep", "Look", "Take"], correct: "Share" },
    { word: "Réussir", options: ["Succeed", "Fail", "Stop", "Talk"], correct: "Succeed" },
    { word: "Fermer", options: ["Close", "Open", "Talk", "Look"], correct: "Close" },
    { word: "Emprunter", options: ["Borrow", "Lend", "Give", "Take"], correct: "Borrow" },
    { word: "Rentrer", options: ["Go out", "Go in", "Stay", "Leave"], correct: "Go in" },
    { word: "Attirer", options: ["Push", "Pull", "Attract", "Repel"], correct: "Attract" },
    { word: "Aller", options: ["Go", "Stay", "Walk", "Talk"], correct: "Go" },
    { word: "Connaître", options: ["Know", "Meet", "Talk", "See"], correct: "Know" },
    { word: "Conduire", options: ["Drive", "Walk", "Run", "Talk"], correct: "Drive" },
    { word: "Lire", options: ["Read", "Write", "Talk", "Listen"], correct: "Read" },
    { word: "Écrire", options: ["Write", "Speak", "Listen", "Think"], correct: "Write" },
    { word: "Faire", options: ["Do", "Make", "Talk", "Look"], correct: "Do" },
    { word: "Avoir", options: ["Have", "Be", "Do", "Make"], correct: "Have" },
    { word: "Être", options: ["Be", "Have", "Do", "Make"], correct: "Be" },
    { word: "Voir", options: ["See", "Hear", "Talk", "Walk"], correct: "See" },
    { word: "Entendre", options: ["Hear", "See", "Talk", "Walk"], correct: "Hear" },
    { word: "Rire", options: ["Laugh", "Cry", "Talk", "Think"], correct: "Laugh" },
    { word: "Pleurer", options: ["Cry", "Laugh", "Talk", "See"], correct: "Cry" },
    { word: "Se lever", options: ["Sit down", "Stand up", "Jump", "Walk"], correct: "Stand up" },
    { word: "Se coucher", options: ["Lie down", "Stand up", "Sit down", "Jump"], correct: "Lie down" },
    { word: "Se réveiller", options: ["Wake up", "Sleep", "Talk", "Walk"], correct: "Wake up" },
    { word: "Se reposer", options: ["Rest", "Walk", "Talk", "Play"], correct: "Rest" },
    { word: "Douter", options: ["Believe", "Doubt", "Talk", "Look"], correct: "Doubt" },
    { word: "Souffrir", options: ["Suffer", "Help", "Talk", "Laugh"], correct: "Suffer" },
    { word: "Enseigner", options: ["Teach", "Learn", "Talk", "Write"], correct: "Teach" },
    { word: "Chercher", options: ["Search", "Find", "Look", "Talk"], correct: "Search" },
    { word: "Cacher", options: ["Hide", "Find", "Give", "Take"], correct: "Hide" },
    { word: "S'occuper", options: ["Take care", "Avoid", "Talk", "Leave"], correct: "Take care" },
    { word: "Améliorer", options: ["Improve", "Destroy", "Talk", "Leave"], correct: "Improve" },
    { word: "Changer", options: ["Change", "Stay", "Look", "Talk"], correct: "Change" },
    { word: "Obliger", options: ["Force", "Allow", "Talk", "Think"], correct: "Force" },
    { word: "Accepter", options: ["Reject", "Accept", "Talk", "Look"], correct: "Accept" },
    { word: "Changer", options: ["Change", "Keep", "Take", "Look"], correct: "Change" },
    { word: "Recevoir", options: ["Send", "Receive", "Look", "Talk"], correct: "Receive" },
    { word: "Fuir", options: ["Run", "Stay", "Walk", "Talk"], correct: "Run" },
    { word: "Décider", options: ["Decide", "Avoid", "Talk", "Look"], correct: "Decide" },
    { word: "Définir", options: ["Define", "Describe", "Look", "Talk"], correct: "Define" }
    ],
    B2: [
        { word: "Soutenir", options: ["Support", "Reject", "Speak", "Listen"], correct: "Support" },
    { word: "Éviter", options: ["Avoid", "Accept", "Look", "Choose"], correct: "Avoid" },
    { word: "Prendre en compte", options: ["Take into account", "Ignore", "Decide", "Look"], correct: "Take into account" },
    { word: "Réfléchir", options: ["Think", "Talk", "Speak", "See"], correct: "Think" },
    { word: "Ressentir", options: ["Feel", "Forget", "Take", "Speak"], correct: "Feel" },
    { word: "Impliquer", options: ["Involve", "Exclude", "Take", "Speak"], correct: "Involve" },
    { word: "Soumettre", options: ["Submit", "Reject", "Allow", "Take"], correct: "Submit" },
    { word: "Constater", options: ["Observe", "Ignore", "Ask", "Talk"], correct: "Observe" },
    { word: "Analyser", options: ["Analyze", "Explain", "Look", "See"], correct: "Analyze" },
    { word: "Mener", options: ["Lead", "Follow", "Walk", "Talk"], correct: "Lead" },
    { word: "Démontrer", options: ["Demonstrate", "Hide", "Think", "See"], correct: "Demonstrate" },
    { word: "Élaborer", options: ["Elaborate", "Simplify", "Walk", "Speak"], correct: "Elaborate" },
    { word: "Clarifier", options: ["Clarify", "Confuse", "Take", "Speak"], correct: "Clarify" },
    { word: "Apprécier", options: ["Appreciate", "Dislike", "Talk", "Speak"], correct: "Appreciate" },
    { word: "Réaliser", options: ["Realize", "Forget", "See", "Speak"], correct: "Realize" },
    { word: "Participer", options: ["Participate", "Observe", "Avoid", "Talk"], correct: "Participate" },
    { word: "Suggérer", options: ["Suggest", "Reject", "Accept", "See"], correct: "Suggest" },
    { word: "Évader", options: ["Escape", "Enter", "Look", "Talk"], correct: "Escape" },
    { word: "Confirmer", options: ["Confirm", "Deny", "Speak", "Walk"], correct: "Confirm" },
    { word: "Expliquer", options: ["Explain", "Confuse", "Talk", "Listen"], correct: "Explain" },
    { word: "Faire face", options: ["Face", "Avoid", "Walk", "Speak"], correct: "Face" },
    { word: "Préciser", options: ["Specify", "Generalize", "Talk", "Speak"], correct: "Specify" },
    { word: "Approfondir", options: ["Deepen", "Simplify", "Look", "Talk"], correct: "Deepen" },
    { word: "Envisager", options: ["Consider", "Reject", "Think", "Speak"], correct: "Consider" },
    { word: "Assurer", options: ["Ensure", "Doubt", "Speak", "Walk"], correct: "Ensure" },
    { word: "S'intéresser", options: ["Interest", "Ignore", "Talk", "Look"], correct: "Interest" },
    { word: "Renoncer", options: ["Give up", "Continue", "Talk", "Walk"], correct: "Give up" },
    { word: "Renforcer", options: ["Strengthen", "Weaken", "Talk", "Walk"], correct: "Strengthen" },
    { word: "Considérer", options: ["Consider", "Reject", "Speak", "Walk"], correct: "Consider" },
    { word: "Convaincre", options: ["Convince", "Reject", "Speak", "Look"], correct: "Convince" },
    { word: "Prendre soin", options: ["Take care", "Neglect", "Speak", "Look"], correct: "Take care" },
    { word: "Compléter", options: ["Complete", "Start", "Stop", "Talk"], correct: "Complete" },
    { word: "Corriger", options: ["Correct", "Make mistakes", "Talk", "Walk"], correct: "Correct" },
    { word: "Renouer", options: ["Reconnect", "Break", "Talk", "Walk"], correct: "Reconnect" },
    { word: "Devenir", options: ["Become", "Stay", "Go", "Leave"], correct: "Become" },
    { word: "Anticiper", options: ["Anticipate", "Ignore", "Talk", "Speak"], correct: "Anticipate" },
    { word: "Réaliser", options: ["Achieve", "Fail", "Talk", "See"], correct: "Achieve" },
    { word: "Mener à bien", options: ["Carry out", "Reject", "See", "Talk"], correct: "Carry out" },
    { word: "Soutenir", options: ["Support", "Reject", "Talk", "Walk"], correct: "Support" },
    { word: "Exiger", options: ["Require", "Give", "Talk", "Speak"], correct: "Require" },
    { word: "Connaître", options: ["Know", "Meet", "Talk", "Look"], correct: "Know" },
    { word: "Repousser", options: ["Postpone", "Continue", "Talk", "Speak"], correct: "Postpone" },
    { word: "Permettre", options: ["Allow", "Reject", "Talk", "Speak"], correct: "Allow" },
    { word: "Décrire", options: ["Describe", "Ignore", "Talk", "Look"], correct: "Describe" },
    { word: "Conseiller", options: ["Advise", "Reject", "Talk", "Look"], correct: "Advise" },
    { word: "Modifier", options: ["Modify", "Keep", "Talk", "Look"], correct: "Modify" },
    { word: "Répartir", options: ["Distribute", "Gather", "Talk", "Speak"], correct: "Distribute" },
    { word: "Exposer", options: ["Expose", "Cover", "Talk", "Look"], correct: "Expose" },
    { word: "Calculer", options: ["Calculate", "Guess", "Talk", "Speak"], correct: "Calculate" },
    { word: "Effectuer", options: ["Perform", "Avoid", "Talk", "Speak"], correct: "Perform" },
    { word: "Agir", options: ["Act", "Wait", "Talk", "Look"], correct: "Act" },
    { word: "Compliquer", options: ["Complicate", "Simplify", "Talk", "Look"], correct: "Complicate" },
    { word: "Obliger", options: ["Force", "Allow", "Talk", "Look"], correct: "Force" },
    { word: "Éviter", options: ["Avoid", "Accept", "Talk", "Look"], correct: "Avoid" },
    { word: "Expliquer", options: ["Explain", "Confuse", "Talk", "Look"], correct: "Explain" },
    { word: "Diviser", options: ["Divide", "Combine", "Talk", "Look"], correct: "Divide" },
    { word: "Arrêter", options: ["Stop", "Start", "Talk", "Look"], correct: "Stop" },
    { word: "Soumettre", options: ["Submit", "Reject", "Talk", "Look"], correct: "Submit" },
    { word: "Distinguer", options: ["Distinguish", "Blend", "Talk", "Look"], correct: "Distinguish" },
    { word: "Ajouter", options: ["Add", "Remove", "Talk", "Look"], correct: "Add" },
    { word: "Informer", options: ["Inform", "Ignore", "Talk", "Look"], correct: "Inform" },{ word: "Gérer", options: ["Manage", "Destroy", "Build", "Speak"], correct: "Manage" },
    { word: "Concevoir", options: ["Design", "Reject", "Look", "Build"], correct: "Design" },
    { word: "Complimenter", options: ["Compliment", "Ignore", "Blame", "Criticize"], correct: "Compliment" },
    { word: "Transformer", options: ["Transform", "Keep", "Destroy", "Look"], correct: "Transform" },
    { word: "Accueillir", options: ["Welcome", "Leave", "Blame", "Look"], correct: "Welcome" },
    { word: "Distinguer", options: ["Distinguish", "Confuse", "Blend", "Look"], correct: "Distinguish" },
    { word: "Réaliser", options: ["Realize", "Forget", "Look", "Ignore"], correct: "Realize" },
    { word: "Négocier", options: ["Negotiate", "Argue", "Reject", "Discuss"], correct: "Negotiate" },
    { word: "Mélanger", options: ["Mix", "Separate", "Observe", "Look"], correct: "Mix" },
    { word: "Sélectionner", options: ["Select", "Reject", "Talk", "Look"], correct: "Select" },
    { word: "Soutenir", options: ["Support", "Reject", "Overcome", "See"], correct: "Support" },
    { word: "Obliger", options: ["Force", "Allow", "Ask", "Talk"], correct: "Force" },
    { word: "Partager", options: ["Share", "Keep", "Tell", "Speak"], correct: "Share" },
    { word: "Réussir", options: ["Succeed", "Fail", "Give up", "See"], correct: "Succeed" },
    { word: "Préférer", options: ["Prefer", "Dislike", "Accept", "Talk"], correct: "Prefer" },
    { word: "Assumer", options: ["Assume", "Deny", "Talk", "Look"], correct: "Assume" },
    { word: "Construire", options: ["Build", "Destroy", "Look", "See"], correct: "Build" },
    { word: "Expliquer", options: ["Explain", "Ignore", "Talk", "Walk"], correct: "Explain" },
    { word: "Obtenir", options: ["Obtain", "Give", "See", "Walk"], correct: "Obtain" },
    { word: "Calculer", options: ["Calculate", "Guess", "See", "Look"], correct: "Calculate" },
    { word: "Prendre", options: ["Take", "Give", "Reject", "Talk"], correct: "Take" },
    { word: "Faire face", options: ["Face", "Avoid", "Look", "See"], correct: "Face" },
    { word: "Élargir", options: ["Expand", "Limit", "Talk", "Look"], correct: "Expand" },
    { word: "Développer", options: ["Develop", "Hinder", "Talk", "Walk"], correct: "Develop" },
    { word: "Impliquer", options: ["Involve", "Exclude", "Ignore", "Look"], correct: "Involve" },
    { word: "Augmenter", options: ["Increase", "Decrease", "Look", "See"], correct: "Increase" },
    { word: "Bénéficier", options: ["Benefit", "Lose", "Ignore", "Talk"], correct: "Benefit" },
    { word: "Allumer", options: ["Turn on", "Turn off", "Look", "Talk"], correct: "Turn on" },
    { word: "Rappeler", options: ["Remind", "Forget", "See", "Talk"], correct: "Remind" },
    { word: "Partager", options: ["Share", "Keep", "Avoid", "Talk"], correct: "Share" },
    { word: "Respecter", options: ["Respect", "Ignore", "Talk", "Look"], correct: "Respect" },
    { word: "Soumettre", options: ["Submit", "Reject", "Allow", "Speak"], correct: "Submit" },
    { word: "Exiger", options: ["Demand", "Give", "Talk", "Walk"], correct: "Demand" },
    { word: "Considérer", options: ["Consider", "Reject", "Look", "See"], correct: "Consider" },
    { word: "Imposer", options: ["Impose", "Accept", "Talk", "Look"], correct: "Impose" },
    { word: "Accepter", options: ["Accept", "Reject", "Talk", "Look"], correct: "Accept" },
    { word: "Critiquer", options: ["Criticize", "Praise", "Talk", "Look"], correct: "Criticize" },
    { word: "Ressentir", options: ["Feel", "Ignore", "Look", "See"], correct: "Feel" },
    { word: "Consommer", options: ["Consume", "Save", "Look", "Talk"], correct: "Consume" },
    { word: "Compléter", options: ["Complete", "Start", "Stop", "Look"], correct: "Complete" },
    { word: "Éviter", options: ["Avoid", "Accept", "Talk", "Look"], correct: "Avoid" },
    { word: "Réaliser", options: ["Achieve", "Fail", "Talk", "See"], correct: "Achieve" },
    { word: "Améliorer", options: ["Improve", "Damage", "Talk", "See"], correct: "Improve" },
    { word: "Changer", options: ["Change", "Stay", "Talk", "Look"], correct: "Change" },
    { word: "Discuter", options: ["Discuss", "Avoid", "Talk", "Look"], correct: "Discuss" },
    { word: "Retirer", options: ["Withdraw", "Add", "Look", "Talk"], correct: "Withdraw" },
    { word: "Apprendre", options: ["Learn", "Forget", "Talk", "Look"], correct: "Learn" },
    { word: "Comparer", options: ["Compare", "Look", "Talk", "See"], correct: "Compare" },
    { word: "Emprunter", options: ["Borrow", "Lend", "Talk", "Look"], correct: "Borrow" },
    { word: "Obliger", options: ["Force", "Allow", "Talk", "Look"], correct: "Force" },
    { word: "Signaler", options: ["Signal", "Ignore", "Talk", "Look"], correct: "Signal" },
    { word: "Attendre", options: ["Wait", "Rush", "Talk", "See"], correct: "Wait" },
    { word: "Accomplir", options: ["Accomplish", "Fail", "Talk", "Look"], correct: "Accomplish" },
    { word: "Attirer", options: ["Attract", "Repel", "Talk", "Look"], correct: "Attract" },
    { word: "Réfléchir", options: ["Think", "Talk", "Look", "See"], correct: "Think" },
    { word: "Soutenir", options: ["Support", "Reject", "Look", "Talk"], correct: "Support" },
    { word: "Éliminer", options: ["Eliminate", "Accept", "Talk", "See"], correct: "Eliminate" },
    { word: "Cacher", options: ["Hide", "Reveal", "Talk", "Look"], correct: "Hide" },
    { word: "Prendre", options: ["Take", "Give", "Talk", "See"], correct: "Take" }
    ],
    C1: [
        { word: "Abolir", options: ["Abolish", "Create", "Preserve", "Ignore"], correct: "Abolish" },
    { word: "Révoquer", options: ["Revoke", "Establish", "Support", "Allow"], correct: "Revoke" },
    { word: "Désamorcer", options: ["Defuse", "Trigger", "Accelerate", "Expand"], correct: "Defuse" },
    { word: "Concéder", options: ["Concede", "Argue", "Refuse", "Debate"], correct: "Concede" },
    { word: "Provoquer", options: ["Provoke", "Calm", "Neutralize", "Hinder"], correct: "Provoke" },
    { word: "Altérer", options: ["Alter", "Preserve", "Analyze", "Neglect"], correct: "Alter" },
    { word: "Alléger", options: ["Lighten", "Burden", "Emphasize", "Complicate"], correct: "Lighten" },
    { word: "Féliciter", options: ["Congratulate", "Criticize", "Blame", "Question"], correct: "Congratulate" },
    { word: "Déchiffrer", options: ["Decipher", "Encrypt", "Write", "Ignore"], correct: "Decipher" },
    { word: "Embrouiller", options: ["Confuse", "Clarify", "Explain", "Confirm"], correct: "Confuse" },
    { word: "Implorer", options: ["Implore", "Command", "Allow", "Deny"], correct: "Implore" },
    { word: "Invoquer", options: ["Invoke", "Dismiss", "Prove", "Ignore"], correct: "Invoke" },
    { word: "Restaurer", options: ["Restore", "Destroy", "Alter", "Inspect"], correct: "Restore" },
    { word: "Subvenir", options: ["Support", "Ignore", "Condemn", "Oppose"], correct: "Support" },
    { word: "Dévoiler", options: ["Reveal", "Hide", "Distort", "Forget"], correct: "Reveal" },
    { word: "Répudier", options: ["Repudiate", "Accept", "Welcome", "Support"], correct: "Repudiate" },
    { word: "Conférer", options: ["Confer", "Remove", "Accept", "Deny"], correct: "Confer" },
    { word: "Émerveiller", options: ["Amaze", "Bore", "Disappoint", "Ignore"], correct: "Amaze" },
    { word: "Dissuader", options: ["Dissuade", "Encourage", "Propose", "Allow"], correct: "Dissuade" },
    { word: "Augurer", options: ["Predict", "Doubt", "Confirm", "Deny"], correct: "Predict" },
    { word: "Exhorter", options: ["Exhort", "Discourage", "Condemn", "Avoid"], correct: "Exhort" },
    { word: "Tergiverser", options: ["Procrastinate", "Act", "Explain", "Accelerate"], correct: "Procrastinate" },
    { word: "Revendiquer", options: ["Claim", "Reject", "Deny", "Question"], correct: "Claim" },
    { word: "Contester", options: ["Challenge", "Accept", "Ignore", "Confirm"], correct: "Challenge" },
    { word: "Fustiger", options: ["Criticize", "Praise", "Support", "Welcome"], correct: "Criticize" },
    { word: "Exacerber", options: ["Exacerbate", "Mitigate", "Explain", "Control"], correct: "Exacerbate" },
    { word: "Aborder", options: ["Address", "Ignore", "Dismiss", "Neglect"], correct: "Address" },
    { word: "Clarifier", options: ["Clarify", "Confuse", "Complicate", "Avoid"], correct: "Clarify" },
    { word: "Récuser", options: ["Refute", "Accept", "Question", "Propose"], correct: "Refute" },
    { word: "Aspirer", options: ["Aspire", "Avoid", "Neglect", "Dismiss"], correct: "Aspire" },
    { word: "Amorcer", options: ["Initiate", "Conclude", "Pause", "Deter"], correct: "Initiate" },
    { word: "Refondre", options: ["Revamp", "Preserve", "Criticize", "Avoid"], correct: "Revamp" },
    { word: "Réprimander", options: ["Reprimand", "Congratulate", "Ignore", "Praise"], correct: "Reprimand" },
    { word: "Contempler", options: ["Contemplate", "Avoid", "Ignore", "Refuse"], correct: "Contemplate" },
    { word: "Aggraver", options: ["Worsen", "Mitigate", "Resolve", "Improve"], correct: "Worsen" },
    { word: "Simplifier", options: ["Simplify", "Complicate", "Question", "Hinder"], correct: "Simplify" },
    { word: "Confondre", options: ["Confuse", "Understand", "Deny", "Prove"], correct: "Confuse" },
    { word: "Harmoniser", options: ["Harmonize", "Disturb", "Neglect", "Dismiss"], correct: "Harmonize" },
    { word: "Renouer", options: ["Reestablish", "Sever", "Disrupt", "Forget"], correct: "Reestablish" },
    { word: "Réhabiliter", options: ["Rehabilitate", "Condemn", "Dismiss", "Neglect"], correct: "Rehabilitate" },
    { word: "Déplorer", options: ["Lament", "Celebrate", "Ignore", "Dismiss"], correct: "Lament" },
    { word: "Aménager", options: ["Arrange", "Destroy", "Neglect", "Avoid"], correct: "Arrange" },
    { word: "Persuader", options: ["Persuade", "Dissuade", "Reject", "Dismiss"], correct: "Persuade" },
    { word: "Reconstituer", options: ["Reconstruct", "Destroy", "Ignore", "Avoid"], correct: "Reconstruct" },
    { word: "Nuancer", options: ["Refine", "Simplify", "Dismiss", "Ignore"], correct: "Refine" },
    { word: "Privilégier", options: ["Favor", "Ignore", "Dismiss", "Oppose"], correct: "Favor" },
    { word: "Illustrer", options: ["Illustrate", "Complicate", "Confuse", "Dismiss"], correct: "Illustrate" },
    { word: "Renoncer", options: ["Renounce", "Accept", "Approve", "Welcome"], correct: "Renounce" },
    { word: "Démystifier", options: ["Demystify", "Confuse", "Complicate", "Question"], correct: "Demystify" },
    { word: "Pallier", options: ["Alleviate", "Worsen", "Ignore", "Avoid"], correct: "Alleviate" },
    { word: "Consolider", options: ["Strengthen", "Weaken", "Hinder", "Reject"], correct: "Strengthen" },
    { word: "Décentraliser", options: ["Decentralize", "Centralize", "Neglect", "Oppose"], correct: "Decentralize" },
    { word: "Innover", options: ["Innovate", "Preserve", "Reject", "Destroy"], correct: "Innovate" },
    { word: "Rédiger", options: ["Draft", "Erase", "Dismiss", "Rewrite"], correct: "Draft" },{ word: "Parvenir", options: ["Achieve", "Ignore", "Fail", "Retreat"], correct: "Achieve" },
    { word: "Élucider", options: ["Clarify", "Confuse", "Ignore", "Complicate"], correct: "Clarify" },
    { word: "Mettre en exergue", options: ["Highlight", "Diminish", "Ignore", "Oppose"], correct: "Highlight" },
    { word: "Réitérer", options: ["Reiterate", "Forget", "Deny", "Simplify"], correct: "Reiterate" },
    { word: "Renforcer", options: ["Strengthen", "Weaken", "Complicate", "Dismiss"], correct: "Strengthen" },
    { word: "Amalgamer", options: ["Merge", "Separate", "Simplify", "Dismiss"], correct: "Merge" },
    { word: "Susciter", options: ["Elicit", "Dismiss", "Ignore", "Disrupt"], correct: "Elicit" },
    { word: "Différer", options: ["Postpone", "Accelerate", "Ignore", "Dismiss"], correct: "Postpone" },
    { word: "Anticiper", options: ["Anticipate", "React", "Procrastinate", "Ignore"], correct: "Anticipate" },
    { word: "Atténuer", options: ["Mitigate", "Worsen", "Accelerate", "Confuse"], correct: "Mitigate" },
    { word: "Détenir", options: ["Detain", "Release", "Ignore", "Support"], correct: "Detain" },
    { word: "Accroître", options: ["Increase", "Reduce", "Maintain", "Delay"], correct: "Increase" },
    { word: "S’efforcer", options: ["Strive", "Relax", "Abandon", "Ignore"], correct: "Strive" },
    { word: "Résorber", options: ["Eliminate", "Create", "Increase", "Ignore"], correct: "Eliminate" },
    { word: "Revigorer", options: ["Revitalize", "Weaken", "Ignore", "Oppress"], correct: "Revitalize" },
    { word: "Appréhender", options: ["Understand", "Ignore", "Complicate", "Disregard"], correct: "Understand" },
    { word: "Corréler", options: ["Correlate", "Separate", "Ignore", "Exclude"], correct: "Correlate" },
    { word: "Délibérer", options: ["Deliberate", "Decide", "Rush", "Dismiss"], correct: "Deliberate" },
    { word: "Optimiser", options: ["Optimize", "Neglect", "Complicate", "Hinder"], correct: "Optimize" },
    { word: "Acquiescer", options: ["Agree", "Disagree", "Ignore", "Reject"], correct: "Agree" },
    { word: "Convenir", options: ["Agree", "Argue", "Reject", "Refuse"], correct: "Agree" },
    { word: "Divulguer", options: ["Disclose", "Hide", "Confuse", "Ignore"], correct: "Disclose" },
    { word: "Incarner", options: ["Embody", "Reject", "Dismiss", "Avoid"], correct: "Embody" },
    { word: "Exploiter", options: ["Exploit", "Ignore", "Preserve", "Dismiss"], correct: "Exploit" },
    { word: "Assimiler", options: ["Assimilate", "Oppose", "Forget", "Separate"], correct: "Assimilate" },
    { word: "Insinuer", options: ["Suggest", "State", "Confirm", "Ignore"], correct: "Suggest" },
    { word: "Aguerrir", options: ["Toughen", "Weaken", "Relax", "Ignore"], correct: "Toughen" },
    { word: "Endosser", options: ["Assume", "Reject", "Ignore", "Complicate"], correct: "Assume" },
    { word: "Subjuguer", options: ["Captivate", "Repel", "Ignore", "Dismiss"], correct: "Captivate" },
    { word: "Démolir", options: ["Demolish", "Build", "Repair", "Ignore"], correct: "Demolish" },
    { word: "Allouer", options: ["Allocate", "Withdraw", "Ignore", "Refuse"], correct: "Allocate" },
    { word: "Moduler", options: ["Adjust", "Fix", "Hinder", "Ignore"], correct: "Adjust" },
    { word: "Rationaliser", options: ["Streamline", "Complicate", "Distort", "Ignore"], correct: "Streamline" },
    { word: "Consolider", options: ["Strengthen", "Break", "Weaken", "Avoid"], correct: "Strengthen" },
    { word: "Converger", options: ["Converge", "Diverge", "Separate", "Ignore"], correct: "Converge" },
    { word: "Infirmer", options: ["Invalidate", "Validate", "Ignore", "Support"], correct: "Invalidate" },
    { word: "Progresser", options: ["Progress", "Recede", "Ignore", "Hinder"], correct: "Progress" },
    { word: "Illustrer", options: ["Illustrate", "Complicate", "Ignore", "Forget"], correct: "Illustrate" },
    { word: "Restituer", options: ["Restore", "Steal", "Ignore", "Dismiss"], correct: "Restore" },
    { word: "Revaloriser", options: ["Revalue", "Neglect", "Dismiss", "Weaken"], correct: "Revalue" },
    { word: "Déployer", options: ["Deploy", "Disassemble", "Ignore", "Dismiss"], correct: "Deploy" },
    { word: "Augmenter", options: ["Increase", "Reduce", "Maintain", "Delay"], correct: "Increase" },
    { word: "Minimiser", options: ["Downplay", "Exaggerate", "Confuse", "Dismiss"], correct: "Downplay" },
    { word: "Supplanter", options: ["Supplant", "Support", "Assist", "Neglect"], correct: "Supplant" },
    { word: "Rehausser", options: ["Enhance", "Diminish", "Oppress", "Dismiss"], correct: "Enhance" },
    { word: "Subventionner", options: ["Subsidize", "Tax", "Oppose", "Ignore"], correct: "Subsidize" },
    { word: "Décentraliser", options: ["Decentralize", "Centralize", "Control", "Neglect"], correct: "Decentralize" },
    { word: "Inscrire", options: ["Enroll", "Reject", "Withdraw", "Avoid"], correct: "Enroll" },
    { word: "Réitérer", options: ["Reiterate", "Ignore", "Question", "Dismiss"], correct: "Reiterate" },
    { word: "Réactualiser", options: ["Update", "Forget", "Diminish", "Neglect"], correct: "Update" },
    { word: "Consigner", options: ["Record", "Erase", "Ignore", "Disperse"], correct: "Record" }
    ],
    C2: [
        { word: "Apothéose", options: ["Climax", "Decline", "Origin", "Contradiction"], correct: "Climax" },
    { word: "Subrepticement", options: ["Surreptitiously", "Obviously", "Loudly", "Deliberately"], correct: "Surreptitiously" },
    { word: "Inénarrable", options: ["Indescribable", "Trivial", "Forgettable", "Ordinary"], correct: "Indescribable" },
    { word: "Pérégrination", options: ["Wandering", "Destination", "Discovery", "Planning"], correct: "Wandering" },
    { word: "Procrastination", options: ["Delay", "Haste", "Efficiency", "Neglect"], correct: "Delay" },
    { word: "Évanescent", options: ["Fleeting", "Enduring", "Powerful", "Permanent"], correct: "Fleeting" },
    { word: "Onirique", options: ["Dreamlike", "Realistic", "Disturbing", "Chaotic"], correct: "Dreamlike" },
    { word: "Flagornerie", options: ["Flattery", "Criticism", "Honesty", "Silence"], correct: "Flattery" },
    { word: "Intrinsèque", options: ["Intrinsic", "Extrinsic", "Artificial", "External"], correct: "Intrinsic" },
    { word: "Déshérence", options: ["Abandonment", "Inheritance", "Success", "Ownership"], correct: "Abandonment" },
    { word: "Disparate", options: ["Dissimilar", "Harmonious", "Equal", "Uniform"], correct: "Dissimilar" },
    { word: "Transcender", options: ["Transcend", "Limit", "Confine", "Hinder"], correct: "Transcend" },
    { word: "Incommensurable", options: ["Immeasurable", "Minor", "Comparable", "Insignificant"], correct: "Immeasurable" },
    { word: "Anachronique", options: ["Outdated", "Modern", "Timely", "Contemporary"], correct: "Outdated" },
    { word: "Démiurge", options: ["Creator", "Destroyer", "Follower", "Observer"], correct: "Creator" },
    { word: "Imprescriptible", options: ["Inalienable", "Conditional", "Temporary", "Negotiable"], correct: "Inalienable" },
    { word: "Misanthrope", options: ["Hater of humanity", "Lover of humanity", "Optimist", "Philanthropist"], correct: "Hater of humanity" },
    { word: "Quintessence", options: ["Essence", "Irrelevance", "Outline", "Surface"], correct: "Essence" },
    { word: "Métamorphose", options: ["Transformation", "Stagnation", "Reversion", "Simplification"], correct: "Transformation" },
    { word: "Opprobe", options: ["Disgrace", "Honor", "Respect", "Admiration"], correct: "Disgrace" },
    { word: "Expédient", options: ["Convenient", "Unfeasible", "Unreasonable", "Inconvenient"], correct: "Convenient" },
    { word: "Atermoiement", options: ["Procrastination", "Action", "Resolution", "Finality"], correct: "Procrastination" },
    { word: "Dithyrambique", options: ["Eulogistic", "Critical", "Dismissive", "Cynical"], correct: "Eulogistic" },
    { word: "Obsolescence", options: ["Obsolescence", "Relevance", "Evolution", "Renovation"], correct: "Obsolescence" },
    { word: "Vicissitude", options: ["Ups and downs", "Stability", "Predictability", "Constancy"], correct: "Ups and downs" },
    { word: "Obséquieux", options: ["Obsequious", "Defiant", "Independent", "Blunt"], correct: "Obsequious" },
    { word: "Hiératique", options: ["Hieratic", "Casual", "Informal", "Nonchalant"], correct: "Hieratic" },
    { word: "Épistémologie", options: ["Study of knowledge", "Study of life", "Study of language", "Study of society"], correct: "Study of knowledge" },
    { word: "Superfétatoire", options: ["Superfluous", "Necessary", "Essential", "Useful"], correct: "Superfluous" },
    { word: "Invétéré", options: ["Deep-rooted", "New", "Temporary", "Fleeting"], correct: "Deep-rooted" },
    { word: "Prolixité", options: ["Wordiness", "Conciseness", "Brevity", "Silence"], correct: "Wordiness" },
    { word: "Turpitude", options: ["Depravity", "Virtue", "Innocence", "Decency"], correct: "Depravity" },
    { word: "Immuable", options: ["Unchanging", "Changeable", "Dynamic", "Volatile"], correct: "Unchanging" },
    { word: "Inexorable", options: ["Relentless", "Flexible", "Compromising", "Forgiving"], correct: "Relentless" },
    { word: "Paroxysme", options: ["Climax", "Decline", "Beginning", "Trough"], correct: "Climax" },
    { word: "Ressentiment", options: ["Resentment", "Forgiveness", "Happiness", "Neutrality"], correct: "Resentment" },
    { word: "Pusillanime", options: ["Timid", "Courageous", "Bold", "Reckless"], correct: "Timid" },
    { word: "Ambages", options: ["Evasiveness", "Clarity", "Directness", "Simplicity"], correct: "Evasiveness" },
    { word: "Cacophonie", options: ["Cacophony", "Harmony", "Silence", "Peace"], correct: "Cacophony" },
    { word: "Corroborer", options: ["Corroborate", "Contradict", "Negate", "Dispute"], correct: "Corroborate" },
    { word: "Sémillant", options: ["Sparkling", "Dull", "Lifeless", "Depressed"], correct: "Sparkling" },
    { word: "Vitupérer", options: ["Criticize", "Praise", "Ignore", "Applaud"], correct: "Criticize" },
    { word: "Spoliation", options: ["Plunder", "Gift", "Charity", "Creation"], correct: "Plunder" },
    { word: "Rocambolesque", options: ["Extraordinary", "Ordinary", "Boring", "Trivial"], correct: "Extraordinary" },
    { word: "Sagacité", options: ["Shrewdness", "Ignorance", "Foolishness", "Naivety"], correct: "Shrewdness" },
    { word: "Pléthorique", options: ["Excessive", "Scarce", "Minimal", "Lacking"], correct: "Excessive" },
    { word: "Stupéfaction", options: ["Astonishment", "Boredom", "Indifference", "Sadness"], correct: "Astonishment" },{ word: "Antépénultième", options: ["Third from last", "Second", "Last", "Middle"], correct: "Third from last" },
    { word: "Hypotypose", options: ["Vivid description", "Criticism", "Confusion", "Simplification"], correct: "Vivid description" },
    { word: "Lénifiant", options: ["Soothing", "Agitating", "Unpleasant", "Worrying"], correct: "Soothing" },
    { word: "Obnubilé", options: ["Obsessed", "Unaware", "Detached", "Uninterested"], correct: "Obsessed" },
    { word: "Thuriféraire", options: ["Flatterer", "Critic", "Neutral party", "Observer"], correct: "Flatterer" },
    { word: "Inchoatif", options: ["Initial", "Conclusive", "Erroneous", "Final"], correct: "Initial" },
    { word: "Truculent", options: ["Colorful", "Dull", "Ordinary", "Bleak"], correct: "Colorful" },
    { word: "Quérulence", options: ["Litigiousness", "Peacefulness", "Honesty", "Friendliness"], correct: "Litigiousness" },
    { word: "Efflorescence", options: ["Blossoming", "Decay", "Ending", "Decline"], correct: "Blossoming" },
    { word: "Hiémal", options: ["Wintry", "Summery", "Autumnal", "Springlike"], correct: "Wintry" },
    { word: "Amphigouri", options: ["Nonsense", "Truth", "Clarity", "Wisdom"], correct: "Nonsense" },
    { word: "Térébrant", options: ["Piercing", "Shallow", "Smooth", "Gentle"], correct: "Piercing" },
    { word: "Apodictique", options: ["Certain", "Uncertain", "Hypothetical", "Doubtful"], correct: "Certain" },
    { word: "Métempsychose", options: ["Reincarnation", "Death", "Oblivion", "Creation"], correct: "Reincarnation" },
    { word: "Palimpseste", options: ["Rewritten text", "Original text", "Story", "Article"], correct: "Rewritten text" },
    { word: "Ouroboros", options: ["Self-reflexivity", "Beginning", "End", "Continuity"], correct: "Self-reflexivity" },
    { word: "Phylactère", options: ["Speech bubble", "Amulet", "Textbook", "Guide"], correct: "Speech bubble" },
    { word: "Lugubre", options: ["Gloomy", "Cheerful", "Bright", "Neutral"], correct: "Gloomy" },
    { word: "Objurgation", options: ["Rebuke", "Praise", "Approval", "Encouragement"], correct: "Rebuke" },
    { word: "Pusillanimité", options: ["Cowardice", "Bravery", "Stubbornness", "Indifference"], correct: "Cowardice" },
    { word: "Hiérarchie", options: ["Hierarchy", "Equality", "Randomness", "Freedom"], correct: "Hierarchy" },
    { word: "Anacoluthe", options: ["Syntax error", "Metaphor", "Personification", "Hyperbole"], correct: "Syntax error" },
    { word: "Logorrhée", options: ["Wordiness", "Silence", "Succinctness", "Precision"], correct: "Wordiness" },
    { word: "Magnanimité", options: ["Generosity", "Meanness", "Greed", "Selfishness"], correct: "Generosity" },
    { word: "Onomatopée", options: ["Onomatopoeia", "Alliteration", "Metonymy", "Hyperbole"], correct: "Onomatopoeia" },
    { word: "Misandrie", options: ["Hatred of men", "Hatred of women", "Love of men", "Equality"], correct: "Hatred of men" },
    { word: "Nihilisme", options: ["Nihilism", "Optimism", "Faith", "Confidence"], correct: "Nihilism" },
    { word: "Pandiculation", options: ["Stretching", "Sleeping", "Yawning", "Sitting"], correct: "Stretching" },
    { word: "Tropisme", options: ["Tendency", "Aversion", "Resistance", "Apathy"], correct: "Tendency" },
    { word: "Ubiquité", options: ["Omnipresence", "Absence", "Solitude", "Scarcity"], correct: "Omnipresence" },
    { word: "Xylophage", options: ["Wood-eating", "Meat-eating", "Plant-eating", "Fruit-eating"], correct: "Wood-eating" },
    { word: "Alacrité", options: ["Eagerness", "Lethargy", "Anger", "Indifference"], correct: "Eagerness" },
    { word: "Effritement", options: ["Crumbling", "Strengthening", "Rebuilding", "Repair"], correct: "Crumbling" },
    { word: "Déréliction", options: ["Abandonment", "Support", "Connection", "Unity"], correct: "Abandonment" },
    { word: "Sempiternel", options: ["Eternal", "Short-lived", "Temporary", "Modern"], correct: "Eternal" },
    { word: "Ziggourat", options: ["Temple", "Palace", "Monument", "Pyramid"], correct: "Temple" },
    { word: "Entéléchie", options: ["Fulfillment", "Beginning", "Chaos", "Uncertainty"], correct: "Fulfillment" },
    { word: "Catachrèse", options: ["Misuse of metaphor", "Accurate metaphor", "Literal meaning", "Hyperbole"], correct: "Misuse of metaphor" },
    { word: "Dysenterie", options: ["Dysentery", "Headache", "Fever", "Nausea"], correct: "Dysentery" },
    { word: "Péripatéticien", options: ["Wandering philosopher", "Stationary thinker", "Religious leader", "Soldier"], correct: "Wandering philosopher" },
    { word: "Obsolescent", options: ["Becoming outdated", "Modernizing", "Innovating", "Progressing"], correct: "Becoming outdated" },
    { word: "Volubilité", options: ["Fluency", "Silence", "Confusion", "Inarticulacy"], correct: "Fluency" },
    { word: "Panchronique", options: ["Timeless", "Current", "Ephemeral", "Irrelevant"], correct: "Timeless" },
    { word: "Sycophante", options: ["Toady", "Leader", "Critic", "Hero"], correct: "Toady" },
    { word: "Synalèphe", options: ["Elision", "Division", "Expansion", "Amplification"], correct: "Elision" },
    { word: "Épenthèse", options: ["Insertion of a sound", "Deletion of a sound", "Alteration of meaning", "Shift in tense"], correct: "Insertion of a sound" },
    { word: "Palindrome", options: ["Reads the same backward", "Is a pun", "Is a rhyme", "Is a simile"], correct: "Reads the same backward" }
    ]
};

// French Word of the Day Data
const frenchWordList = [
    { "word": "Chien", "meaning": "Dog", "plural": "Chiens", "indefinite": "un", "definite": "le" },
    { "word": "Livre", "meaning": "Book", "plural": "Livres", "indefinite": "un", "definite": "le" },
    { "word": "Mer", "meaning": "Sea", "plural": "Mers", "indefinite": "une", "definite": "la" },
    { "word": "Chat", "meaning": "Cat", "plural": "Chats", "indefinite": "un", "definite": "le" },
    { "word": "Fleur", "meaning": "Flower", "plural": "Fleurs", "indefinite": "une", "definite": "la" },
    { "word": "Voiture", "meaning": "Car", "plural": "Voitures", "indefinite": "une", "definite": "la" },
    { "word": "Maison", "meaning": "House", "plural": "Maisons", "indefinite": "une", "definite": "la" },
    { "word": "Arbre", "meaning": "Tree", "plural": "Arbres", "indefinite": "un", "definite": "l'" },
    { "word": "Chaise", "meaning": "Chair", "plural": "Chaises", "indefinite": "une", "definite": "la" },
    { "word": "Table", "meaning": "Table", "plural": "Tables", "indefinite": "une", "definite": "la" },
    { "word": "Pomme", "meaning": "Apple", "plural": "Pommes", "indefinite": "une", "definite": "la" },
    { "word": "École", "meaning": "School", "plural": "Écoles", "indefinite": "une", "definite": "l'" },
    { "word": "Bureau", "meaning": "Office", "plural": "Bureaux", "indefinite": "un", "definite": "le" },
    { "word": "Fenêtre", "meaning": "Window", "plural": "Fenêtres", "indefinite": "une", "definite": "la" },
    { "word": "Chapeau", "meaning": "Hat", "plural": "Chapeaux", "indefinite": "un", "definite": "le" },
    { "word": "Robe", "meaning": "Dress", "plural": "Robes", "indefinite": "une", "definite": "la" },
    { "word": "Vêtement", "meaning": "Clothing", "plural": "Vêtements", "indefinite": "un", "definite": "le" },
    { "word": "Pain", "meaning": "Bread", "plural": "Pains", "indefinite": "un", "definite": "le" },
    { "word": "Fromage", "meaning": "Cheese", "plural": "Fromages", "indefinite": "un", "definite": "le" },
    { "word": "Poisson", "meaning": "Fish", "plural": "Poissons", "indefinite": "un", "definite": "le" },
    { "word": "Lait", "meaning": "Milk", "plural": "Laits", "indefinite": "un", "definite": "le" },
    { "word": "Eau", "meaning": "Water", "plural": "Eaux", "indefinite": "de l'", "definite": "l'" },
    { "word": "Ciel", "meaning": "Sky", "plural": "Ciels", "indefinite": "un", "definite": "le" },
    { "word": "Étoile", "meaning": "Star", "plural": "Étoiles", "indefinite": "une", "definite": "l'" },
    { "word": "Montagne", "meaning": "Mountain", "plural": "Montagnes", "indefinite": "une", "definite": "la" },
    { "word": "Rivière", "meaning": "River", "plural": "Rivières", "indefinite": "une", "definite": "la" },
    { "word": "Plage", "meaning": "Beach", "plural": "Plages", "indefinite": "une", "definite": "la" },
    { "word": "Ville", "meaning": "City", "plural": "Villes", "indefinite": "une", "definite": "la" },
    { "word": "Pays", "meaning": "Country", "plural": "Pays", "indefinite": "un", "definite": "le" },
    { "word": "Rue", "meaning": "Street", "plural": "Rues", "indefinite": "une", "definite": "la" },
    { "word": "Route", "meaning": "Road", "plural": "Routes", "indefinite": "une", "definite": "la" },
    { "word": "Parc", "meaning": "Park", "plural": "Parcs", "indefinite": "un", "definite": "le" },
    { "word": "Jardin", "meaning": "Garden", "plural": "Jardins", "indefinite": "un", "definite": "le" },
    { "word": "Armoire", "meaning": "Wardrobe", "plural": "Armoires", "indefinite": "une", "definite": "l'" },
    { "word": "Tapis", "meaning": "Carpet", "plural": "Tapis", "indefinite": "un", "definite": "le" },
    { "word": "Télévision", "meaning": "Television", "plural": "Télévisions", "indefinite": "une", "definite": "la" },
    { "word": "Ordinateur", "meaning": "Computer", "plural": "Ordinateurs", "indefinite": "un", "definite": "l'" },
    { "word": "Téléphone", "meaning": "Phone", "plural": "Téléphones", "indefinite": "un", "definite": "le" },
    { "word": "Lampe", "meaning": "Lamp", "plural": "Lampes", "indefinite": "une", "definite": "la" },
    { "word": "Sac", "meaning": "Bag", "plural": "Sacs", "indefinite": "un", "definite": "le" },
    { "word": "Clé", "meaning": "Key", "plural": "Clés", "indefinite": "une", "definite": "la" },
    { "word": "Carte", "meaning": "Card", "plural": "Cartes", "indefinite": "une", "definite": "la" },
    { "word": "Monnaie", "meaning": "Money", "plural": "Monnaies", "indefinite": "une", "definite": "la" },
    { "word": "Chiffre", "meaning": "Number", "plural": "Chiffres", "indefinite": "un", "definite": "le" },
    { "word": "Heure", "meaning": "Hour", "plural": "Heures", "indefinite": "une", "definite": "l'" },
    { "word": "Minute", "meaning": "Minute", "plural": "Minutes", "indefinite": "une", "definite": "la" },
    { "word": "Seconde", "meaning": "Second", "plural": "Secondes", "indefinite": "une", "definite": "la" },
    { "word": "Jour", "meaning": "Day", "plural": "Jours", "indefinite": "un", "definite": "le" },
    { "word": "Semaine", "meaning": "Week", "plural": "Semaines", "indefinite": "une", "definite": "la" },
    { "word": "Mois", "meaning": "Month", "plural": "Mois", "indefinite": "un", "definite": "le" },
    { "word": "Année", "meaning": "Year", "plural": "Années", "indefinite": "une", "definite": "l'" },
    { "word": "Été", "meaning": "Summer", "plural": "Étés", "indefinite": "un", "definite": "l'" },
    { "word": "Hiver", "meaning": "Winter", "plural": "Hivers", "indefinite": "un", "definite": "l'" },
    { "word": "Printemps", "meaning": "Spring", "plural": "Printemps", "indefinite": "un", "definite": "le" },
    { "word": "Automne", "meaning": "Autumn", "plural": "Automnes", "indefinite": "un", "definite": "l'" },
    { "word": "Mercredi", "meaning": "Wednesday", "plural": "Mercredis", "indefinite": "un", "definite": "le" },
    { "word": "Jeudi", "meaning": "Thursday", "plural": "Jeudis", "indefinite": "un", "definite": "le" },
    { "word": "Vendredi", "meaning": "Friday", "plural": "Vendredis", "indefinite": "un", "definite": "le" },
    { "word": "Samedi", "meaning": "Saturday", "plural": "Samedis", "indefinite": "un", "definite": "le" },
    { "word": "Dimanche", "meaning": "Sunday", "plural": "Dimanches", "indefinite": "un", "definite": "le" },
    { "word": "Lundi", "meaning": "Monday", "plural": "Lundis", "indefinite": "un", "definite": "le" },
    { "word": "Soleil", "meaning": "Sun", "plural": "Soleils", "indefinite": "un", "definite": "le" },
    { "word": "Lune", "meaning": "Moon", "plural": "Lunes", "indefinite": "une", "definite": "la" },
    { "word": "Ciel", "meaning": "Sky", "plural": "Ciels", "indefinite": "un", "definite": "le" },
    { "word": "Nuage", "meaning": "Cloud", "plural": "Nuages", "indefinite": "un", "definite": "le" },
    { "word": "Pluie", "meaning": "Rain", "plural": "Pluies", "indefinite": "une", "definite": "la" },
    { "word": "Neige", "meaning": "Snow", "plural": "Neiges", "indefinite": "une", "definite": "la" },
    { "word": "Vent", "meaning": "Wind", "plural": "Vents", "indefinite": "un", "definite": "le" },
    { "word": "Température", "meaning": "Temperature", "plural": "Températures", "indefinite": "une", "definite": "la" },
    { "word": "Climat", "meaning": "Climate", "plural": "Climats", "indefinite": "un", "definite": "le" },
    { "word": "Plante", "meaning": "Plant", "plural": "Plantes", "indefinite": "une", "definite": "la" },
    { "word": "Arbre", "meaning": "Tree", "plural": "Arbres", "indefinite": "un", "definite": "le" },
    { "word": "Forêt", "meaning": "Forest", "plural": "Forêts", "indefinite": "une", "definite": "la" },
    { "word": "Île", "meaning": "Island", "plural": "Îles", "indefinite": "une", "definite": "l'" },{ "word": "Chocolat", "meaning": "Chocolate", "plural": "Chocolats", "indefinite": "un", "definite": "le" },
    { "word": "Fruit", "meaning": "Fruit", "plural": "Fruits", "indefinite": "un", "definite": "le" },
    { "word": "Vélo", "meaning": "Bicycle", "plural": "Vélos", "indefinite": "un", "definite": "le" },
    { "word": "Télescope", "meaning": "Telescope", "plural": "Télescopes", "indefinite": "un", "definite": "le" },
    { "word": "Piano", "meaning": "Piano", "plural": "Pianos", "indefinite": "un", "definite": "le" },
    { "word": "Guitare", "meaning": "Guitar", "plural": "Guitares", "indefinite": "une", "definite": "la" },
    { "word": "Violon", "meaning": "Violin", "plural": "Violons", "indefinite": "un", "definite": "le" },
    { "word": "Sculpture", "meaning": "Sculpture", "plural": "Sculptures", "indefinite": "une", "definite": "la" },
    { "word": "Peinture", "meaning": "Painting", "plural": "Peintures", "indefinite": "une", "definite": "la" },
    { "word": "Chanson", "meaning": "Song", "plural": "Chansons", "indefinite": "une", "definite": "la" },
    { "word": "Film", "meaning": "Film", "plural": "Films", "indefinite": "un", "definite": "le" },
    { "word": "Théâtre", "meaning": "Theater", "plural": "Théâtres", "indefinite": "un", "definite": "le" },
    { "word": "Danse", "meaning": "Dance", "plural": "Danses", "indefinite": "une", "definite": "la" },
    { "word": "Poème", "meaning": "Poem", "plural": "Poèmes", "indefinite": "un", "definite": "le" },
    { "word": "Roman", "meaning": "Novel", "plural": "Romans", "indefinite": "un", "definite": "le" },
    { "word": "Écrivain", "meaning": "Writer", "plural": "Écrivains", "indefinite": "un", "definite": "l'" },
    { "word": "Journal", "meaning": "Newspaper", "plural": "Journaux", "indefinite": "un", "definite": "le" },
    { "word": "Magazine", "meaning": "Magazine", "plural": "Magazines", "indefinite": "un", "definite": "le" },
    { "word": "Téléphone", "meaning": "Phone", "plural": "Téléphones", "indefinite": "un", "definite": "le" },
    { "word": "Appareil", "meaning": "Device", "plural": "Appareils", "indefinite": "un", "definite": "l'" },
    { "word": "Écran", "meaning": "Screen", "plural": "Écrans", "indefinite": "un", "definite": "l'" },
    { "word": "Clé", "meaning": "Key", "plural": "Clés", "indefinite": "une", "definite": "la" },
    { "word": "Cartable", "meaning": "Schoolbag", "plural": "Cartables", "indefinite": "un", "definite": "le" },
    { "word": "Bouteille", "meaning": "Bottle", "plural": "Bouteilles", "indefinite": "une", "definite": "la" },
    { "word": "Verre", "meaning": "Glass", "plural": "Verres", "indefinite": "un", "definite": "le" },
    { "word": "Cuillère", "meaning": "Spoon", "plural": "Cuillères", "indefinite": "une", "definite": "la" },
    { "word": "Fourchette", "meaning": "Fork", "plural": "Fourchettes", "indefinite": "une", "definite": "la" },
    { "word": "Couteau", "meaning": "Knife", "plural": "Couteaux", "indefinite": "un", "definite": "le" },
    { "word": "Assiette", "meaning": "Plate", "plural": "Assiettes", "indefinite": "une", "definite": "la" },
    { "word": "Serviette", "meaning": "Napkin", "plural": "Serviettes", "indefinite": "une", "definite": "la" },
    { "word": "Fenêtre", "meaning": "Window", "plural": "Fenêtres", "indefinite": "une", "definite": "la" },
    { "word": "Porte", "meaning": "Door", "plural": "Portes", "indefinite": "une", "definite": "la" },
    { "word": "Clé", "meaning": "Key", "plural": "Clés", "indefinite": "une", "definite": "la" },
    { "word": "Miroir", "meaning": "Mirror", "plural": "Miroirs", "indefinite": "un", "definite": "le" },
    { "word": "Toilette", "meaning": "Toilet", "plural": "Toilettes", "indefinite": "une", "definite": "la" },
    { "word": "Salle", "meaning": "Room", "plural": "Salles", "indefinite": "une", "definite": "la" },
    { "word": "Cuisine", "meaning": "Kitchen", "plural": "Cuisines", "indefinite": "une", "definite": "la" },
    { "word": "Salon", "meaning": "Living Room", "plural": "Salons", "indefinite": "un", "definite": "le" },
    { "word": "Chambre", "meaning": "Bedroom", "plural": "Chambres", "indefinite": "une", "definite": "la" },
    { "word": "Couloir", "meaning": "Corridor", "plural": "Couloirs", "indefinite": "un", "definite": "le" },
    { "word": "Garage", "meaning": "Garage", "plural": "Garages", "indefinite": "un", "definite": "le" },
    { "word": "Jardin", "meaning": "Garden", "plural": "Jardins", "indefinite": "un", "definite": "le" },
    { "word": "Bureau", "meaning": "Desk", "plural": "Bureaux", "indefinite": "un", "definite": "le" },
    { "word": "Étagère", "meaning": "Shelf", "plural": "Étagères", "indefinite": "une", "definite": "la" },
    { "word": "Lampe", "meaning": "Lamp", "plural": "Lampes", "indefinite": "une", "definite": "la" },
    { "word": "Chaise", "meaning": "Chair", "plural": "Chaises", "indefinite": "une", "definite": "la" },
    { "word": "Canapé", "meaning": "Couch", "plural": "Canapés", "indefinite": "un", "definite": "le" },
    { "word": "Télévision", "meaning": "Television", "plural": "Télévisions", "indefinite": "une", "definite": "la" },
    { "word": "Radio", "meaning": "Radio", "plural": "Radios", "indefinite": "une", "definite": "la" },
    { "word": "Ordinateur", "meaning": "Computer", "plural": "Ordinateurs", "indefinite": "un", "definite": "l'" },
    { "word": "Bureau", "meaning": "Office", "plural": "Bureaux", "indefinite": "un", "definite": "le" },
    { "word": "Drapeau", "meaning": "Flag", "plural": "Drapeaux", "indefinite": "un", "definite": "le" },
    { "word": "Mappemonde", "meaning": "Globe", "plural": "Mappemondes", "indefinite": "une", "definite": "la" },
    { "word": "Planète", "meaning": "Planet", "plural": "Planètes", "indefinite": "une", "definite": "la" },
    { "word": "Étoile", "meaning": "Star", "plural": "Étoiles", "indefinite": "une", "definite": "l'" },
    { "word": "Soleil", "meaning": "Sun", "plural": "Soleils", "indefinite": "un", "definite": "le" },
    { "word": "Lune", "meaning": "Moon", "plural": "Lunes", "indefinite": "une", "definite": "la" },
    { "word": "Nuage", "meaning": "Cloud", "plural": "Nuages", "indefinite": "un", "definite": "le" },
    { "word": "Pluie", "meaning": "Rain", "plural": "Pluies", "indefinite": "une", "definite": "la" },
    { "word": "Neige", "meaning": "Snow", "plural": "Neiges", "indefinite": "une", "definite": "la" },
    { "word": "Vent", "meaning": "Wind", "plural": "Vents", "indefinite": "un", "definite": "le" },
    { "word": "Température", "meaning": "Temperature", "plural": "Températures", "indefinite": "une", "definite": "la" },
    { "word": "Climat", "meaning": "Climate", "plural": "Climats", "indefinite": "un", "definite": "le" },
    { "word": "Plante", "meaning": "Plant", "plural": "Plantes", "indefinite": "une", "definite": "la" },
    { "word": "Forêt", "meaning": "Forest", "plural": "Forêts", "indefinite": "une", "definite": "la" },
    { "word": "Arbre", "meaning": "Tree", "plural": "Arbres", "indefinite": "un", "definite": "le" },
    { "word": "Montagne", "meaning": "Mountain", "plural": "Montagnes", "indefinite": "une", "definite": "la" },
    { "word": "Rivière", "meaning": "River", "plural": "Rivières", "indefinite": "une", "definite": "la" },
    { "word": "Chapeau", "meaning": "Hat", "plural": "Chapeaux", "indefinite": "un", "definite": "le" },
    { "word": "Étoile", "meaning": "Star", "plural": "Étoiles", "indefinite": "une", "definite": "l'" },
    { "word": "Bureau", "meaning": "Desk", "plural": "Bureaux", "indefinite": "un", "definite": "le" },
    { "word": "Télévision", "meaning": "Television", "plural": "Télévisions", "indefinite": "une", "definite": "la" },
    { "word": "Sac", "meaning": "Bag", "plural": "Sacs", "indefinite": "un", "definite": "le" },
    { "word": "Poisson", "meaning": "Fish", "plural": "Poissons", "indefinite": "un", "definite": "le" },
    { "word": "Clé", "meaning": "Key", "plural": "Clés", "indefinite": "une", "definite": "la" },
    { "word": "Lait", "meaning": "Milk", "plural": "Laits", "indefinite": "un", "definite": "le" },
    { "word": "Vélo", "meaning": "Bicycle", "plural": "Vélos", "indefinite": "un", "definite": "le" },
    { "word": "Plage", "meaning": "Beach", "plural": "Plages", "indefinite": "une", "definite": "la" },
    { "word": "Journal", "meaning": "Newspaper", "plural": "Journaux", "indefinite": "un", "definite": "le" },
    { "word": "Piano", "meaning": "Piano", "plural": "Pianos", "indefinite": "un", "definite": "le" },
    { "word": "Armoire", "meaning": "Wardrobe", "plural": "Armoires", "indefinite": "une", "definite": "l'" },
    { "word": "Film", "meaning": "Film", "plural": "Films", "indefinite": "un", "definite": "le" },
    { "word": "Forêt", "meaning": "Forest", "plural": "Forêts", "indefinite": "une", "definite": "la" },
    { "word": "Route", "meaning": "Road", "plural": "Routes", "indefinite": "une", "definite": "la" },
    { "word": "Chambre", "meaning": "Bedroom", "plural": "Chambres", "indefinite": "une", "definite": "la" },
    { "word": "Couloir", "meaning": "Corridor", "plural": "Couloirs", "indefinite": "un", "definite": "le" },
    { "word": "Château", "meaning": "Castle", "plural": "Châteaux", "indefinite": "un", "definite": "le" },
    { "word": "Montagne", "meaning": "Mountain", "plural": "Montagnes", "indefinite": "une", "definite": "la" },
    { "word": "Plante", "meaning": "Plant", "plural": "Plantes", "indefinite": "une", "definite": "la" },
    { "word": "Nuage", "meaning": "Cloud", "plural": "Nuages", "indefinite": "un", "definite": "le" },
    { "word": "Cloche", "meaning": "Bell", "plural": "Cloches", "indefinite": "une", "definite": "la" },
    { "word": "Soleil", "meaning": "Sun", "plural": "Soleils", "indefinite": "un", "definite": "le" },
    { "word": "Lune", "meaning": "Moon", "plural": "Lunes", "indefinite": "une", "definite": "la" },
    { "word": "Chiffre", "meaning": "Number", "plural": "Chiffres", "indefinite": "un", "definite": "le" },
    { "word": "Saison", "meaning": "Season", "plural": "Saisons", "indefinite": "une", "definite": "la" },
    { "word": "Jupe", "meaning": "Skirt", "plural": "Jupes", "indefinite": "une", "definite": "la" },
    { "word": "Fête", "meaning": "Party", "plural": "Fêtes", "indefinite": "une", "definite": "la" },
    { "word": "Cadeau", "meaning": "Gift", "plural": "Cadeaux", "indefinite": "un", "definite": "le" },
    { "word": "Métier", "meaning": "Profession", "plural": "Métiers", "indefinite": "un", "definite": "le" },
    { "word": "Oiseau", "meaning": "Bird", "plural": "Oiseaux", "indefinite": "un", "definite": "l'" },
    { "word": "Voile", "meaning": "Sail", "plural": "Voiles", "indefinite": "un", "definite": "le" },
    { "word": "Drapeau", "meaning": "Flag", "plural": "Drapeaux", "indefinite": "un", "definite": "le" },
    { "word": "Glace", "meaning": "Ice", "plural": "Glaces", "indefinite": "une", "definite": "la" },
    { "word": "Barque", "meaning": "Boat", "plural": "Barques", "indefinite": "une", "definite": "la" },
    { "word": "Éclair", "meaning": "Lightning", "plural": "Éclairs", "indefinite": "un", "definite": "l'" },
    { "word": "Tempête", "meaning": "Storm", "plural": "Tempêtes", "indefinite": "une", "definite": "la" },
    { "word": "Fleuriste", "meaning": "Florist", "plural": "Fleuristes", "indefinite": "un", "definite": "le" },
    { "word": "Dîner", "meaning": "Dinner", "plural": "Dîners", "indefinite": "un", "definite": "le" },
    { "word": "Sablier", "meaning": "Hourglass", "plural": "Sablier", "indefinite": "un", "definite": "le" },
    { "word": "Magasin", "meaning": "Store", "plural": "Magasins", "indefinite": "un", "definite": "le" },
    { "word": "Champ", "meaning": "Field", "plural": "Champs", "indefinite": "un", "definite": "le" },
    { "word": "Mélodie", "meaning": "Melody", "plural": "Mélodies", "indefinite": "une", "definite": "la" },
    { "word": "Pétale", "meaning": "Petal", "plural": "Pétales", "indefinite": "un", "definite": "le" },
    { "word": "Livre", "meaning": "Pound", "plural": "Livres", "indefinite": "un", "definite": "le" },
    { "word": "Café", "meaning": "Coffee", "plural": "Cafés", "indefinite": "un", "definite": "le" },
    { "word": "Biscuit", "meaning": "Biscuit", "plural": "Biscuits", "indefinite": "un", "definite": "le" },
    { "word": "Sac", "meaning": "Bag", "plural": "Sacs", "indefinite": "un", "definite": "le" },
    { "word": "Sous-sol", "meaning": "Basement", "plural": "Sous-sols", "indefinite": "un", "definite": "le" },
    { "word": "Toit", "meaning": "Roof", "plural": "Toits", "indefinite": "un", "definite": "le" },
    { "word": "Neige", "meaning": "Snow", "plural": "Neiges", "indefinite": "une", "definite": "la" },
    { "word": "Fenêtre", "meaning": "Window", "plural": "Fenêtres", "indefinite": "une", "definite": "la" },
    { "word": "Rivière", "meaning": "River", "plural": "Rivières", "indefinite": "une", "definite": "la" },
    { "word": "Plage", "meaning": "Beach", "plural": "Plages", "indefinite": "une", "definite": "la" },
    { "word": "Étoile", "meaning": "Star", "plural": "Étoiles", "indefinite": "une", "definite": "l'" },
    { "word": "Bateau", "meaning": "Boat", "plural": "Bateaux", "indefinite": "un", "definite": "le" },
    { "word": "Tapis", "meaning": "Carpet", "plural": "Tapis", "indefinite": "un", "definite": "le" },
    { "word": "Chien", "meaning": "Dog", "plural": "Chiens", "indefinite": "un", "definite": "le" },
    { "word": "Chat", "meaning": "Cat", "plural": "Chats", "indefinite": "un", "definite": "le" },
    { "word": "Cheval", "meaning": "Horse", "plural": "Chevaux", "indefinite": "un", "definite": "le" },
    { "word": "Fleur", "meaning": "Flower", "plural": "Fleurs", "indefinite": "une", "definite": "la" },
    { "word": "Soleil", "meaning": "Sun", "plural": "Soleils", "indefinite": "un", "definite": "le" },
    { "word": "Vent", "meaning": "Wind", "plural": "Vents", "indefinite": "un", "definite": "le" },
    { "word": "Arbre", "meaning": "Tree", "plural": "Arbres", "indefinite": "un", "definite": "l'" },
    { "word": "Plomb", "meaning": "Lead", "plural": "Plombs", "indefinite": "un", "definite": "le" },
    { "word": "Papillon", "meaning": "Butterfly", "plural": "Papillons", "indefinite": "un", "definite": "le" },
    { "word": "Chaise", "meaning": "Chair", "plural": "Chaises", "indefinite": "une", "definite": "la" },
    { "word": "Table", "meaning": "Table", "plural": "Tables", "indefinite": "une", "definite": "la" },
    { "word": "Cuisine", "meaning": "Kitchen", "plural": "Cuisines", "indefinite": "une", "definite": "la" },
    { "word": "Voiture", "meaning": "Car", "plural": "Voitures", "indefinite": "une", "definite": "la" },
    { "word": "Vélo", "meaning": "Bicycle", "plural": "Vélos", "indefinite": "un", "definite": "le" },
    { "word": "Montre", "meaning": "Watch", "plural": "Montres", "indefinite": "une", "definite": "la" },
    { "word": "Légume", "meaning": "Vegetable", "plural": "Légumes", "indefinite": "un", "definite": "le" },
    { "word": "Poisson", "meaning": "Fish", "plural": "Poissons", "indefinite": "un", "definite": "le" },
    { "word": "Oiseau", "meaning": "Bird", "plural": "Oiseaux", "indefinite": "un", "definite": "l'" },
    { "word": "Pomme", "meaning": "Apple", "plural": "Pommes", "indefinite": "une", "definite": "la" },
    { "word": "Banane", "meaning": "Banana", "plural": "Bananes", "indefinite": "une", "definite": "la" },
    { "word": "Bière", "meaning": "Beer", "plural": "Bières", "indefinite": "une", "definite": "la" },
    { "word": "Vin", "meaning": "Wine", "plural": "Vins", "indefinite": "un", "definite": "le" },
    { "word": "Crayon", "meaning": "Pencil", "plural": "Crayons", "indefinite": "un", "definite": "le" },
    { "word": "Livre", "meaning": "Book", "plural": "Livres", "indefinite": "un", "definite": "le" },
    { "word": "Ordinateur", "meaning": "Computer", "plural": "Ordinateurs", "indefinite": "un", "definite": "l'" },
    { "word": "Écran", "meaning": "Screen", "plural": "Écrans", "indefinite": "un", "definite": "le" }
];

module.exports = { frenchQuizData, frenchWordList };