// German Quiz Data
const germanQuizData = {
    A1: [
        { word: "Haus", options: ["Car", "Dog", "Tree", "House"], correct: "House" },
    { word: "Katze", options: ["Bird", "Dog", "Fish", "Cat"], correct: "Cat" },
    { word: "Auto", options: ["Bus", "Car", "Bike", "Train"], correct: "Car" },
    { word: "Tisch", options: ["Chair", "Door", "Window", "Table"], correct: "Table" },
    { word: "Hund", options: ["Fish", "Dog", "Bird", "Cat"], correct: "Dog" },
    { word: "Buch", options: ["Pen", "Bag", "Paper", "Book"], correct: "Book" },
    { word: "Baum", options: ["Bush", "Tree", "Flower", "Grass"], correct: "Tree" },
    { word: "Stuhl", options: ["Lamp", "Couch", "Table", "Chair"], correct: "Chair" },
    { word: "Fenster", options: ["Wall", "Roof", "Window", "Door"], correct: "Window" },
    { word: "Mensch", options: ["Animal", "Person", "Thing", "Plant"], correct: "Person" },
    { word: "Vogel", options: ["Bird", "Dog", "Cat", "Fish"], correct: "Bird" },
    { word: "Freund", options: ["Friend", "Enemy", "Teacher", "Student"], correct: "Friend" },
    { word: "Apfel", options: ["Apple", "Banana", "Grapes", "Orange"], correct: "Apple" },
    { word: "Stadt", options: ["City", "Country", "Village", "Town"], correct: "City" },
    { word: "Wasser", options: ["Water", "Juice", "Milk", "Tea"], correct: "Water" },
    { word: "Brot", options: ["Bread", "Cheese", "Butter", "Egg"], correct: "Bread" },
    { word: "Hund", options: ["Cat", "Dog", "Bird", "Fish"], correct: "Dog" },
    { word: "Blume", options: ["Flower", "Tree", "Bush", "Grass"], correct: "Flower" },
    { word: "Kind", options: ["Child", "Adult", "Teenager", "Baby"], correct: "Child" },
    { word: "Hemd", options: ["Shirt", "Pants", "Jacket", "Dress"], correct: "Shirt" },
    { word: "Bleistift", options: ["Pen", "Pencil", "Eraser", "Marker"], correct: "Pencil" },
    { word: "Schule", options: ["School", "University", "College", "Library"], correct: "School" },
    { word: "Tasche", options: ["Bag", "Shirt", "Jacket", "Hat"], correct: "Bag" },
    { word: "Garten", options: ["Garden", "House", "Street", "Park"], correct: "Garden" },
    { word: "Frau", options: ["Man", "Woman", "Child", "Boy"], correct: "Woman" },
    { word: "Mutter", options: ["Father", "Mother", "Brother", "Sister"], correct: "Mother" },
    { word: "Vater", options: ["Father", "Mother", "Brother", "Sister"], correct: "Father" },
    { word: "Sonne", options: ["Moon", "Star", "Sun", "Cloud"], correct: "Sun" },
    { word: "Licht", options: ["Light", "Dark", "Fire", "Lamp"], correct: "Light" },
    { word: "Tee", options: ["Tea", "Coffee", "Juice", "Water"], correct: "Tea" },
    { word: "Woche", options: ["Week", "Month", "Day", "Year"], correct: "Week" },
    { word: "Jahr", options: ["Month", "Week", "Day", "Year"], correct: "Year" },
    { word: "Hund", options: ["Dog", "Cat", "Bird", "Fish"], correct: "Dog" },
    { word: "Regen", options: ["Rain", "Snow", "Wind", "Cloud"], correct: "Rain" },
    { word: "Sommer", options: ["Winter", "Fall", "Spring", "Summer"], correct: "Summer" },
    { word: "Herbst", options: ["Fall", "Summer", "Spring", "Winter"], correct: "Fall" },
    { word: "Winter", options: ["Winter", "Spring", "Fall", "Summer"], correct: "Winter" },
    { word: "Frühling", options: ["Spring", "Winter", "Fall", "Summer"], correct: "Spring" },
    { word: "Berge", options: ["Mountains", "Seas", "Lakes", "Rivers"], correct: "Mountains" },
    { word: "Meer", options: ["Ocean", "Sea", "Lake", "River"], correct: "Sea" },
    { word: "Fluss", options: ["River", "Lake", "Ocean", "Sea"], correct: "River" },
    { word: "Straße", options: ["Street", "Park", "Road", "Alley"], correct: "Street" },
    { word: "Auto", options: ["Car", "Truck", "Bus", "Train"], correct: "Car" },
    { word: "Fahrrad", options: ["Bike", "Bus", "Car", "Train"], correct: "Bike" },
    { word: "Zug", options: ["Train", "Car", "Bike", "Bus"], correct: "Train" },
    { word: "Bus", options: ["Bus", "Car", "Bike", "Train"], correct: "Bus" },
    { word: "Flughafen", options: ["Airport", "Station", "Port", "Harbor"], correct: "Airport" },
    { word: "Hafen", options: ["Harbor", "Port", "Station", "Airport"], correct: "Harbor" },
    { word: "Bahnhof", options: ["Train station", "Bus station", "Airport", "Port"], correct: "Train station" },
    { word: "Geld", options: ["Money", "Coin", "Card", "Bill"], correct: "Money" },
    { word: "Taschenlampe", options: ["Flashlight", "Lamp", "Candle", "Torch"], correct: "Flashlight" },
    { word: "Schlüssel", options: ["Key", "Lock", "Door", "Window"], correct: "Key" },
    { word: "Telefon", options: ["Phone", "Computer", "Tablet", "Watch"], correct: "Phone" },
    { word: "Computer", options: ["Computer", "Phone", "Tablet", "Watch"], correct: "Computer" },
    { word: "Uhr", options: ["Clock", "Watch", "Phone", "Computer"], correct: "Watch" },
    { word: "Zeit", options: ["Time", "Date", "Week", "Month"], correct: "Time" },
    { word: "Montag", options: ["Monday", "Sunday", "Tuesday", "Wednesday"], correct: "Monday" },
    { word: "Dienstag", options: ["Tuesday", "Monday", "Wednesday", "Thursday"], correct: "Tuesday" },
    { word: "Mittwoch", options: ["Wednesday", "Tuesday", "Thursday", "Friday"], correct: "Wednesday" },
    { word: "Donnerstag", options: ["Thursday", "Friday", "Saturday", "Monday"], correct: "Thursday" },
    { word: "Freitag", options: ["Friday", "Saturday", "Sunday", "Thursday"], correct: "Friday" },
    { word: "Samstag", options: ["Saturday", "Sunday", "Friday", "Monday"], correct: "Saturday" },
    { word: "Sonntag", options: ["Sunday", "Saturday", "Friday", "Thursday"], correct: "Sunday" },
    { word: "Reise", options: ["Trip", "Journey", "Travel", "Flight"], correct: "Trip" },
    { word: "Flughafen", options: ["Airport", "Station", "Port", "Harbor"], correct: "Airport" },
    { word: "Hotel", options: ["Hotel", "Restaurant", "Cafe", "Bar"], correct: "Hotel" },
    { word: "Restaurant", options: ["Restaurant", "Cafe", "Bar", "Hotel"], correct: "Restaurant" },
    { word: "Cafe", options: ["Cafe", "Bar", "Hotel", "Restaurant"], correct: "Cafe" },
    { word: "Bar", options: ["Bar", "Cafe", "Hotel", "Restaurant"], correct: "Bar" },
    { word: "Essen", options: ["Food", "Drink", "Meal", "Snack"], correct: "Food" },
    { word: "Getränk", options: ["Drink", "Food", "Meal", "Snack"], correct: "Drink" },
    { word: "Kaffee", options: ["Coffee", "Tea", "Juice", "Water"], correct: "Coffee" },
    { word: "Tee", options: ["Tea", "Coffee", "Juice", "Water"], correct: "Tea" },
    { word: "Saft", options: ["Juice", "Water", "Coffee", "Tea"], correct: "Juice" },
    { word: "Wasser", options: ["Water", "Juice", "Milk", "Tea"], correct: "Water" },
    { word: "Blume", options: ["Tree", "Flower", "Bush", "Grass"], correct: "Flower" },
    { word: "Hemd", options: ["Shirt", "Pants", "Jacket", "Dress"], correct: "Shirt" },
    { word: "Bleistift", options: ["Pen", "Pencil", "Eraser", "Marker"], correct: "Pencil" },
    { word: "Schule", options: ["School", "University", "Library", "College"], correct: "School" },
    { word: "Tasche", options: ["Bag", "Jacket", "Shirt", "Hat"], correct: "Bag" },
    { word: "Garten", options: ["Park", "Garden", "Street", "House"], correct: "Garden" },
    { word: "Frau", options: ["Boy", "Woman", "Child", "Man"], correct: "Woman" },
    { word: "Mutter", options: ["Mother", "Father", "Brother", "Sister"], correct: "Mother" },
    { word: "Vater", options: ["Father", "Brother", "Sister", "Mother"], correct: "Father" },
    { word: "Sonne", options: ["Star", "Sun", "Moon", "Cloud"], correct: "Sun" },
    { word: "Licht", options: ["Lamp", "Light", "Dark", "Fire"], correct: "Light" },
    { word: "Tee", options: ["Tea", "Coffee", "Water", "Juice"], correct: "Tea" },
    { word: "Woche", options: ["Month", "Day", "Week", "Year"], correct: "Week" },
    { word: "Jahr", options: ["Month", "Year", "Day", "Week"], correct: "Year" },
    { word: "Regen", options: ["Rain", "Snow", "Wind", "Cloud"], correct: "Rain" },
    { word: "Sommer", options: ["Winter", "Summer", "Spring", "Fall"], correct: "Summer" },
    { word: "Herbst", options: ["Fall", "Winter", "Spring", "Summer"], correct: "Fall" },
    { word: "Winter", options: ["Winter", "Spring", "Fall", "Summer"], correct: "Winter" },
    { word: "Frühling", options: ["Spring", "Winter", "Fall", "Summer"], correct: "Spring" },
    { word: "Berge", options: ["Rivers", "Mountains", "Lakes", "Seas"], correct: "Mountains" },
    { word: "Meer", options: ["Sea", "Lake", "Ocean", "River"], correct: "Sea" },
    { word: "Fluss", options: ["Ocean", "Sea", "River", "Lake"], correct: "River" },
    { word: "Straße", options: ["Street", "Road", "Park", "Alley"], correct: "Street" },
    { word: "Zug", options: ["Car", "Bus", "Bike", "Train"], correct: "Train" },
    { word: "Bus", options: ["Car", "Train", "Bus", "Bike"], correct: "Bus" },
    { word: "Flughafen", options: ["Airport", "Harbor", "Port", "Station"], correct: "Airport" },
    { word: "Hafen", options: ["Station", "Airport", "Port", "Harbor"], correct: "Harbor" },
    { word: "Bahnhof", options: ["Train station", "Bus station", "Airport", "Port"], correct: "Train station" },
    { word: "Geld", options: ["Bill", "Card", "Money", "Coin"], correct: "Money" },
    { word: "Taschenlampe", options: ["Flashlight", "Candle", "Lamp", "Torch"], correct: "Flashlight" },
    { word: "Schlüssel", options: ["Lock", "Door", "Key", "Window"], correct: "Key" },
    { word: "Telefon", options: ["Phone", "Tablet", "Computer", "Watch"], correct: "Phone" },
    { word: "Computer", options: ["Phone", "Tablet", "Watch", "Computer"], correct: "Computer" },
    { word: "Uhr", options: ["Watch", "Clock", "Phone", "Computer"], correct: "Watch" },
    { word: "Zeit", options: ["Date", "Week", "Time", "Month"], correct: "Time" },
    { word: "Montag", options: ["Monday", "Tuesday", "Wednesday", "Thursday"], correct: "Monday" },
    { word: "Dienstag", options: ["Tuesday", "Wednesday", "Thursday", "Friday"], correct: "Tuesday" },
    { word: "Mittwoch", options: ["Wednesday", "Thursday", "Friday", "Tuesday"], correct: "Wednesday" },
    { word: "Donnerstag", options: ["Thursday", "Friday", "Saturday", "Monday"], correct: "Thursday" },
    { word: "Freitag", options: ["Friday", "Saturday", "Sunday", "Thursday"], correct: "Friday" },
    { word: "Samstag", options: ["Saturday", "Sunday", "Monday", "Friday"], correct: "Saturday" },
    { word: "Sonntag", options: ["Sunday", "Saturday", "Friday", "Thursday"], correct: "Sunday" },
    { word: "Reise", options: ["Journey", "Trip", "Travel", "Flight"], correct: "Trip" },
    { word: "Hotel", options: ["Cafe", "Restaurant", "Hotel", "Bar"], correct: "Hotel" },
    { word: "Restaurant", options: ["Hotel", "Cafe", "Restaurant", "Bar"], correct: "Restaurant" },
    { word: "Cafe", options: ["Bar", "Cafe", "Hotel", "Restaurant"], correct: "Cafe" },
    { word: "Bar", options: ["Restaurant", "Cafe", "Bar", "Hotel"], correct: "Bar" },
    { word: "Essen", options: ["Food", "Drink", "Meal", "Snack"], correct: "Food" },
    { word: "Getränk", options: ["Drink", "Food", "Meal", "Snack"], correct: "Drink" },
    { word: "Kaffee", options: ["Tea", "Coffee", "Juice", "Water"], correct: "Coffee" },
    { word: "Saft", options: ["Water", "Tea", "Juice", "Coffee"], correct: "Juice" },
    { word: "Wasser", options: ["Tea", "Coffee", "Water", "Milk"], correct: "Water" },
    { word: "Löffel", options: ["Spoon", "Fork", "Knife", "Plate"], correct: "Spoon" },
    { word: "Gabel", options: ["Fork", "Spoon", "Knife", "Plate"], correct: "Fork" },
    { word: "Messer", options: ["Knife", "Fork", "Spoon", "Plate"], correct: "Knife" },
    { word: "Teller", options: ["Plate", "Cup", "Glass", "Fork"], correct: "Plate" },
    { word: "Schokolade", options: ["Candy", "Chocolate", "Cake", "Fruit"], correct: "Chocolate" },
    { word: "Kuchen", options: ["Cake", "Pie", "Candy", "Cookie"], correct: "Cake" },
    { word: "Obst", options: ["Vegetables", "Fruit", "Meat", "Grain"], correct: "Fruit" },
    { word: "Gemüse", options: ["Meat", "Fruit", "Vegetables", "Grain"], correct: "Vegetables" },
    { word: "Fleisch", options: ["Grain", "Vegetables", "Fruit", "Meat"], correct: "Meat" },
    { word: "Reis", options: ["Grain", "Vegetables", "Meat", "Fruit"], correct: "Grain" },
    { word: "Käse", options: ["Cheese", "Milk", "Butter", "Yogurt"], correct: "Cheese" },
    { word: "Milch", options: ["Milk", "Cheese", "Yogurt", "Butter"], correct: "Milk" },
    { word: "Butter", options: ["Yogurt", "Milk", "Butter", "Cheese"], correct: "Butter" },
    { word: "Joghurt", options: ["Cheese", "Yogurt", "Milk", "Butter"], correct: "Yogurt" },
    { word: "Zucker", options: ["Salt", "Sugar", "Pepper", "Vinegar"], correct: "Sugar" },
    { word: "Salz", options: ["Sugar", "Vinegar", "Salt", "Pepper"], correct: "Salt" },
    { word: "Pfeffer", options: ["Salt", "Sugar", "Pepper", "Vinegar"], correct: "Pepper" },
    { word: "Essig", options: ["Vinegar", "Salt", "Sugar", "Pepper"], correct: "Vinegar" },
    { word: "Abend", options: ["Morning", "Night", "Afternoon", "Evening"], correct: "Evening" },
    { word: "Morgen", options: ["Morning", "Night", "Afternoon", "Evening"], correct: "Morning" },
    { word: "Nacht", options: ["Night", "Morning", "Afternoon", "Evening"], correct: "Night" },
    { word: "Nachmittag", options: ["Morning", "Afternoon", "Night", "Evening"], correct: "Afternoon" },
    { word: "Frühstück", options: ["Breakfast", "Dinner", "Lunch", "Snack"], correct: "Breakfast" },
    { word: "Mittagessen", options: ["Dinner", "Lunch", "Snack", "Breakfast"], correct: "Lunch" },
    { word: "Abendessen", options: ["Dinner", "Snack", "Lunch", "Breakfast"], correct: "Dinner" },
    { word: "Snack", options: ["Dinner", "Snack", "Lunch", "Breakfast"], correct: "Snack" }
    ],
    A2: [
        { word: "Freizeit", options: ["Leisure", "Work", "School", "Homework"], correct: "Leisure" },
    { word: "Arzt", options: ["Doctor", "Nurse", "Patient", "Teacher"], correct: "Doctor" },
    { word: "Krankenhaus", options: ["Hospital", "Clinic", "Pharmacy", "Doctor's office"], correct: "Hospital" },
    { word: "Zukunft", options: ["Past", "Future", "Present", "History"], correct: "Future" },
    { word: "Geschenk", options: ["Gift", "Toy", "Surprise", "Present"], correct: "Gift" },
    { word: "Gesundheit", options: ["Wealth", "Health", "Happiness", "Peace"], correct: "Health" },
    { word: "Büro", options: ["Office", "Home", "School", "Store"], correct: "Office" },
    { word: "Familie", options: ["Family", "Friends", "Neighbors", "Cousins"], correct: "Family" },
    { word: "Auto", options: ["Car", "Bike", "Bus", "Train"], correct: "Car" },
    { word: "Fahrrad", options: ["Bus", "Train", "Bike", "Car"], correct: "Bike" },
    { word: "Stadt", options: ["Town", "City", "Village", "Country"], correct: "City" },
    { word: "Dorf", options: ["Town", "City", "Village", "Country"], correct: "Village" },
    { word: "Essen", options: ["Food", "Drink", "Snack", "Meal"], correct: "Food" },
    { word: "Trinken", options: ["Eating", "Drinking", "Sleeping", "Running"], correct: "Drinking" },
    { word: "Zug", options: ["Bus", "Car", "Train", "Plane"], correct: "Train" },
    { word: "Flughafen", options: ["Harbor", "Airport", "Train station", "Bus stop"], correct: "Airport" },
    { word: "Reise", options: ["Journey", "Trip", "Vacation", "Work"], correct: "Trip" },
    { word: "Urlaub", options: ["Vacation", "Work", "Weekend", "Meeting"], correct: "Vacation" },
    { word: "Tiere", options: ["Animals", "Birds", "Fish", "Pets"], correct: "Animals" },
    { word: "Vogel", options: ["Bird", "Fish", "Cat", "Dog"], correct: "Bird" },
    { word: "Hund", options: ["Cat", "Dog", "Bird", "Fish"], correct: "Dog" },
    { word: "Katze", options: ["Dog", "Cat", "Bird", "Fish"], correct: "Cat" },
    { word: "Fisch", options: ["Bird", "Dog", "Fish", "Cat"], correct: "Fish" },
    { word: "Haus", options: ["House", "Car", "Apartment", "Building"], correct: "House" },
    { word: "Wohnung", options: ["House", "Flat", "Room", "Building"], correct: "Flat" },
    { word: "Zimmer", options: ["Kitchen", "Room", "Bathroom", "Living room"], correct: "Room" },
    { word: "Küche", options: ["Living room", "Kitchen", "Bedroom", "Bathroom"], correct: "Kitchen" },
    { word: "Badezimmer", options: ["Bedroom", "Living room", "Bathroom", "Kitchen"], correct: "Bathroom" },
    { word: "Balkon", options: ["Garden", "Balcony", "Kitchen", "Living room"], correct: "Balcony" },
    { word: "Garten", options: ["Park", "Garden", "Street", "Building"], correct: "Garden" },
    { word: "Straße", options: ["Street", "Building", "Park", "Road"], correct: "Street" },
    { word: "Brücke", options: ["Bridge", "Tunnel", "Road", "Street"], correct: "Bridge" },
    { word: "Weg", options: ["Road", "Path", "Tunnel", "Bridge"], correct: "Path" },
    { word: "Verkehr", options: ["Movement", "Traffic", "Road", "Cars"], correct: "Traffic" },
    { word: "Ampel", options: ["Traffic light", "Road sign", "Crosswalk", "Park"], correct: "Traffic light" },
    { word: "Fahrkarte", options: ["Ticket", "Pass", "Bus", "Card"], correct: "Ticket" },
    { word: "Rechnung", options: ["Invoice", "Receipt", "Receipt", "Bill"], correct: "Invoice" },
    { word: "Preis", options: ["Cost", "Price", "Value", "Amount"], correct: "Price" },
    { word: "Geld", options: ["Money", "Coin", "Credit", "Cash"], correct: "Money" },
    { word: "Bank", options: ["Office", "Bank", "Store", "Cafe"], correct: "Bank" },
    { word: "Supermarkt", options: ["Store", "Supermarket", "Mall", "Market"], correct: "Supermarket" },
    { word: "Laden", options: ["Shop", "Store", "Market", "Supermarket"], correct: "Shop" },
    { word: "Friseur", options: ["Barber", "Doctor", "Teacher", "Hairdresser"], correct: "Hairdresser" },
    { word: "Bäckerei", options: ["Supermarket", "Bakery", "Market", "Shop"], correct: "Bakery" },
    { word: "Apotheke", options: ["Pharmacy", "Supermarket", "Store", "Restaurant"], correct: "Pharmacy" },
    { word: "Restaurant", options: ["Cafe", "Bar", "Restaurant", "Bakery"], correct: "Restaurant" },
    { word: "Kaffee", options: ["Tea", "Coffee", "Juice", "Milk"], correct: "Coffee" },
    { word: "Tee", options: ["Milk", "Coffee", "Tea", "Water"], correct: "Tea" },
    { word: "Wasser", options: ["Juice", "Tea", "Water", "Milk"], correct: "Water" },
    { word: "Saft", options: ["Milk", "Juice", "Water", "Tea"], correct: "Juice" },
    { word: "Frühstück", options: ["Dinner", "Lunch", "Breakfast", "Snack"], correct: "Breakfast" },
    { word: "Mittagessen", options: ["Dinner", "Snack", "Breakfast", "Lunch"], correct: "Lunch" },
    { word: "Abendessen", options: ["Dinner", "Lunch", "Snack", "Breakfast"], correct: "Dinner" },
    { word: "Snack", options: ["Lunch", "Dinner", "Snack", "Breakfast"], correct: "Snack" },
    { word: "Küche", options: ["Living room", "Bathroom", "Kitchen", "Bedroom"], correct: "Kitchen" },
    { word: "Essen", options: ["Food", "Drink", "Snack", "Meal"], correct: "Food" },
    { word: "Buch", options: ["Pen", "Book", "Paper", "Notebook"], correct: "Book" },
    { word: "Stift", options: ["Pen", "Pencil", "Eraser", "Marker"], correct: "Pen" },
    { word: "Papier", options: ["Pen", "Paper", "Notebook", "Book"], correct: "Paper" },
    { word: "Tasche", options: ["Bag", "Shoes", "Shirt", "Hat"], correct: "Bag" },
    { word: "Schlüssel", options: ["Lock", "Window", "Key", "Door"], correct: "Key" },
    { word: "Schrank", options: ["Shelf", "Closet", "Table", "Chair"], correct: "Closet" },
    { word: "Fenster", options: ["Window", "Door", "Roof", "Wall"], correct: "Window" },
    { word: "Tür", options: ["Wall", "Roof", "Door", "Window"], correct: "Door" },
    { word: "Boden", options: ["Floor", "Wall", "Ceiling", "Roof"], correct: "Floor" },
    { word: "Wand", options: ["Ceiling", "Roof", "Wall", "Floor"], correct: "Wall" },
    { word: "Decke", options: ["Ceiling", "Wall", "Roof", "Floor"], correct: "Ceiling" },
    { word: "Woche", options: ["Month", "Week", "Year", "Day"], correct: "Week" },
    { word: "Tag", options: ["Week", "Month", "Day", "Year"], correct: "Day" },
    { word: "Monat", options: ["Year", "Day", "Week", "Month"], correct: "Month" },
    { word: "Jahr", options: ["Month", "Day", "Year", "Week"], correct: "Year" },
    { word: "Freund", options: ["Teacher", "Friend", "Family", "Relative"], correct: "Friend" },
    { word: "Nachbar", options: ["Neighbor", "Friend", "Family", "Relative"], correct: "Neighbor" },
    { word: "Lehrer", options: ["Student", "Teacher", "Friend", "Neighbor"], correct: "Teacher" },
    { word: "Schüler", options: ["Teacher", "Student", "Friend", "Neighbor"], correct: "Student" },
    { word: "Arbeit", options: ["Work", "Study", "Rest", "Play"], correct: "Work" },
    { word: "Pause", options: ["Break", "Class", "Work", "Lunch"], correct: "Break" },
    { word: "Handy", options: ["Phone", "Tablet", "Computer", "Laptop"], correct: "Phone" },
    { word: "Laptop", options: ["Phone", "Laptop", "Tablet", "Computer"], correct: "Laptop" },
    { word: "Tablet", options: ["Phone", "Tablet", "Laptop", "Computer"], correct: "Tablet" },
    { word: "Bäckerei", options: ["Shop", "Restaurant", "Bakery", "Supermarket"], correct: "Bakery" },
    { word: "Bibliothek", options: ["Cafe", "Library", "Park", "Shop"], correct: "Library" },
    { word: "Essen", options: ["Food", "Rest", "Drink", "Sleep"], correct: "Food" },
    { word: "Trinken", options: ["Walk", "Eat", "Drink", "Sleep"], correct: "Drink" },
    { word: "Frühstück", options: ["Snack", "Dinner", "Lunch", "Breakfast"], correct: "Breakfast" },
    { word: "Mittagessen", options: ["Snack", "Dinner", "Lunch", "Breakfast"], correct: "Lunch" },
    { word: "Abendessen", options: ["Snack", "Lunch", "Breakfast", "Dinner"], correct: "Dinner" },
    { word: "Tisch", options: ["Sofa", "Table", "Shelf", "Chair"], correct: "Table" },
    { word: "Stuhl", options: ["Couch", "Chair", "Sofa", "Table"], correct: "Chair" },
    { word: "Fenster", options: ["Door", "Floor", "Window", "Ceiling"], correct: "Window" },
    { word: "Tür", options: ["Window", "Door", "Ceiling", "Floor"], correct: "Door" },
    { word: "Boden", options: ["Wall", "Ceiling", "Floor", "Roof"], correct: "Floor" },
    { word: "Decke", options: ["Wall", "Ceiling", "Floor", "Roof"], correct: "Ceiling" },
    { word: "Himmel", options: ["Moon", "Cloud", "Earth", "Sky"], correct: "Sky" },
    { word: "Erde", options: ["Sky", "Moon", "Earth", "Cloud"], correct: "Earth" },
    { word: "Wasser", options: ["Water", "Earth", "Fire", "Air"], correct: "Water" },
    { word: "Feuer", options: ["Earth", "Water", "Fire", "Air"], correct: "Fire" },
    { word: "Luft", options: ["Air", "Earth", "Fire", "Water"], correct: "Air" },
    { word: "Blume", options: ["Bush", "Tree", "Grass", "Flower"], correct: "Flower" },
    { word: "Baum", options: ["Flower", "Bush", "Tree", "Grass"], correct: "Tree" },
    { word: "Gras", options: ["Bush", "Grass", "Tree", "Flower"], correct: "Grass" },
    { word: "Bus", options: ["Train", "Plane", "Bus", "Car"], correct: "Bus" },
    { word: "Fahrrad", options: ["Train", "Bike", "Car", "Bus"], correct: "Bike" },
    { word: "Taxi", options: ["Train", "Taxi", "Car", "Bus"], correct: "Taxi" },
    { word: "Flughafen", options: ["Train station", "Harbor", "Bus stop", "Airport"], correct: "Airport" },
    { word: "Bahnhof", options: ["Train station", "Bus stop", "Harbor", "Airport"], correct: "Train station" },
    { word: "Schiff", options: ["Car", "Bus", "Boat", "Train"], correct: "Boat" },
    { word: "Hotel", options: ["Shop", "Park", "Hotel", "Museum"], correct: "Hotel" },
    { word: "Restaurant", options: ["Hotel", "Museum", "Restaurant", "Park"], correct: "Restaurant" },
    { word: "Kino", options: ["Cinema", "Museum", "Restaurant", "Theater"], correct: "Cinema" },
    { word: "Theater", options: ["Museum", "Theater", "Cinema", "Restaurant"], correct: "Theater" },
    { word: "Park", options: ["Museum", "Restaurant", "Theater", "Park"], correct: "Park" },
    { word: "Laden", options: ["Park", "Shop", "Hotel", "Museum"], correct: "Shop" },
    { word: "Straße", options: ["Street", "Bus", "Train", "Car"], correct: "Street" },
    { word: "Brücke", options: ["Tunnel", "Street", "Bridge", "House"], correct: "Bridge" },
    { word: "Weg", options: ["Path", "Street", "Bridge", "Road"], correct: "Path" },
    { word: "Verkehr", options: ["Road", "Traffic", "Cars", "Street"], correct: "Traffic" },
    { word: "Ampel", options: ["Street", "Crosswalk", "Sign", "Traffic light"], correct: "Traffic light" },
    { word: "Schule", options: ["University", "School", "Library", "College"], correct: "School" },
    { word: "Lehrer", options: ["Student", "Teacher", "Parent", "Principal"], correct: "Teacher" },
    { word: "Schüler", options: ["Parent", "Teacher", "Student", "Friend"], correct: "Student" },
    { word: "Tafel", options: ["Desk", "Board", "Table", "Chair"], correct: "Board" }
    ],
    B1: [
        { word: "Abenteuer", options: ["Adventure", "Vacation", "Journey", "Holiday"], correct: "Adventure" },
    { word: "Verabredung", options: ["Appointment", "Meeting", "Call", "Dinner"], correct: "Appointment" },
    { word: "Erfahrung", options: ["Knowledge", "Experience", "Learning", "Skill"], correct: "Experience" },
    { word: "Welt", options: ["Earth", "World", "Moon", "Sky"], correct: "World" },
    { word: "Gesellschaft", options: ["Society", "Culture", "Community", "Nation"], correct: "Society" },
    { word: "Zukunft", options: ["Past", "Present", "Future", "Moment"], correct: "Future" },
    { word: "Vergangenheit", options: ["Future", "Past", "Present", "History"], correct: "Past" },
    { word: "Gegenteil", options: ["Opposite", "Similar", "Same", "Different"], correct: "Opposite" },
    { word: "Natur", options: ["Nature", "Environment", "Planet", "World"], correct: "Nature" },
    { word: "Stimmung", options: ["Mood", "Tone", "Feel", "Spirit"], correct: "Mood" },
    { word: "Gefühl", options: ["Feeling", "Thought", "Idea", "Mood"], correct: "Feeling" },
    { word: "Problem", options: ["Solution", "Challenge", "Problem", "Opportunity"], correct: "Problem" },
    { word: "Lösung", options: ["Problem", "Answer", "Solution", "Question"], correct: "Solution" },
    { word: "Wirtschaft", options: ["Economy", "Trade", "Money", "Bank"], correct: "Economy" },
    { word: "Arbeitnehmer", options: ["Employee", "Employer", "Worker", "Owner"], correct: "Employee" },
    { word: "Arbeitsplatz", options: ["Office", "Workplace", "Store", "Factory"], correct: "Workplace" },
    { word: "Fähigkeit", options: ["Skill", "Talent", "Experience", "Ability"], correct: "Skill" },
    { word: "Woche", options: ["Day", "Month", "Week", "Year"], correct: "Week" },
    { word: "Jahr", options: ["Day", "Week", "Month", "Year"], correct: "Year" },
    { word: "Monat", options: ["Day", "Week", "Month", "Year"], correct: "Month" },
    { word: "Freundschaft", options: ["Relationship", "Friendship", "Companionship", "Love"], correct: "Friendship" },
    { word: "Bekanntschaft", options: ["Friend", "Acquaintance", "Companion", "Relative"], correct: "Acquaintance" },
    { word: "Kundendienst", options: ["Customer service", "Support", "Sales", "Store"], correct: "Customer service" },
    { word: "Gespräch", options: ["Discussion", "Conversation", "Talk", "Meeting"], correct: "Conversation" },
    { word: "Einladung", options: ["Invitation", "Request", "Meeting", "Call"], correct: "Invitation" },
    { word: "Ereignis", options: ["Event", "Occurrence", "Meeting", "Action"], correct: "Event" },
    { word: "Fehler", options: ["Mistake", "Problem", "Solution", "Success"], correct: "Mistake" },
    { word: "Herausforderung", options: ["Challenge", "Problem", "Solution", "Task"], correct: "Challenge" },
    { word: "Erfolg", options: ["Achievement", "Failure", "Success", "Task"], correct: "Success" },
    { word: "Hoffnung", options: ["Fear", "Hope", "Wish", "Desire"], correct: "Hope" },
    { word: "Glaube", options: ["Belief", "Faith", "Religion", "Hope"], correct: "Faith" },
    { word: "Wissen", options: ["Knowledge", "Thought", "Feeling", "Idea"], correct: "Knowledge" },
    { word: "Lernen", options: ["Learning", "Teaching", "Studying", "Training"], correct: "Learning" },
    { word: "Schwierigkeit", options: ["Ease", "Difficulty", "Challenge", "Problem"], correct: "Difficulty" },
    { word: "Prozess", options: ["Process", "Task", "Journey", "Action"], correct: "Process" },
    { word: "Erklärung", options: ["Explanation", "Story", "Definition", "Speech"], correct: "Explanation" },
    { word: "Ansicht", options: ["View", "Perspective", "Opinion", "Belief"], correct: "Opinion" },
    { word: "Aussage", options: ["Statement", "Message", "Answer", "Idea"], correct: "Statement" },
    { word: "Bedeutung", options: ["Meaning", "Answer", "Idea", "Statement"], correct: "Meaning" },
    { word: "Zustand", options: ["State", "Condition", "Place", "Moment"], correct: "Condition" },
    { word: "Technologie", options: ["Science", "Technology", "Innovation", "Invention"], correct: "Technology" },
    { word: "Entwicklung", options: ["Growth", "Development", "Process", "Change"], correct: "Development" },
    { word: "Fortschritt", options: ["Progress", "Development", "Growth", "Success"], correct: "Progress" },
    { word: "Wahl", options: ["Choice", "Option", "Decision", "Selection"], correct: "Choice" },
    { word: "Entscheidung", options: ["Decision", "Choice", "Opinion", "Statement"], correct: "Decision" },
    { word: "Verantwortung", options: ["Responsibility", "Duty", "Obligation", "Task"], correct: "Responsibility" },
    { word: "Möglichkeit", options: ["Opportunity", "Possibility", "Chance", "Option"], correct: "Opportunity" },
    { word: "Energie", options: ["Power", "Energy", "Force", "Strength"], correct: "Energy" },
    { word: "Unterschied", options: ["Similarity", "Difference", "Contrast", "Match"], correct: "Difference" },
    { word: "Geschenk", options: ["Present", "Gift", "Toy", "Card"], correct: "Gift" },
    { word: "Einkaufen", options: ["Shopping", "Eating", "Walking", "Running"], correct: "Shopping" },
    { word: "Verhalten", options: ["Behavior", "Action", "Movement", "Response"], correct: "Behavior" },
    { word: "Unfall", options: ["Accident", "Event", "Problem", "Journey"], correct: "Accident" },
    { word: "Erholung", options: ["Rest", "Exercise", "Work", "Leisure"], correct: "Rest" },
    { word: "Geld", options: ["Money", "Paper", "Card", "Value"], correct: "Money" },
    { word: "Kreditkarte", options: ["Debit card", "Cash", "Credit card", "Gift card"], correct: "Credit card" },
    { word: "Rechnung", options: ["Receipt", "Bill", "Order", "Invoice"], correct: "Bill" },
    { word: "Vertrag", options: ["Agreement", "Contract", "Promise", "Deal"], correct: "Contract" },
    { word: "Adresse", options: ["Location", "Street", "Address", "Place"], correct: "Address" },
    { word: "Stadt", options: ["Town", "Village", "City", "Region"], correct: "City" },
    { word: "Land", options: ["Country", "Region", "City", "State"], correct: "Country" },
    { word: "Flughafen", options: ["Bus station", "Airport", "Train station", "Harbor"], correct: "Airport" },
    { word: "Parken", options: ["Walking", "Running", "Parking", "Cycling"], correct: "Parking" },
    { word: "Verkehrsmittel", options: ["Transport", "Road", "Vehicle", "Journey"], correct: "Transport" },
    { word: "Bus", options: ["Car", "Bike", "Train", "Bus"], correct: "Bus" },
    { word: "Zug", options: ["Train", "Car", "Taxi", "Bus"], correct: "Train" },
    { word: "Fahrrad", options: ["Bus", "Bike", "Car", "Train"], correct: "Bike" },
    { word: "Flugzeug", options: ["Plane", "Boat", "Bus", "Train"], correct: "Plane" },
    { word: "Reise", options: ["Journey", "Travel", "Trip", "Adventure"], correct: "Travel" },
    { word: "Urlaub", options: ["Vacation", "Business trip", "Trip", "Holiday"], correct: "Vacation" },
    { word: "Freizeit", options: ["Work", "Leisure", "Rest", "Study"], correct: "Leisure" },
    { word: "Sport", options: ["Exercise", "Sport", "Running", "Gym"], correct: "Sport" },
    { word: "Gesundheit", options: ["Health", "Body", "Energy", "Fitness"], correct: "Health" },
    { word: "Arzt", options: ["Doctor", "Nurse", "Pharmacist", "Patient"], correct: "Doctor" },
    { word: "Krankenhaus", options: ["Hospital", "Clinic", "Pharmacy", "Ambulance"], correct: "Hospital" },
    { word: "Medizin", options: ["Medicine", "Health", "Treatment", "Prescription"], correct: "Medicine" },
    { word: "Schmerzen", options: ["Pain", "Treatment", "Symptom", "Illness"], correct: "Pain" },
    { word: "Symptom", options: ["Sign", "Condition", "Symptom", "Illness"], correct: "Symptom" },
    { word: "Erkältung", options: ["Cold", "Cough", "Flu", "Headache"], correct: "Cold" },
    { word: "Husten", options: ["Cough", "Cold", "Pain", "Fever"], correct: "Cough" },
    { word: "Fieber", options: ["Fever", "Pain", "Cold", "Cough"], correct: "Fever" },
    { word: "Tabelle", options: ["Chart", "Table", "Picture", "Graph"], correct: "Table" },
    { word: "Buch", options: ["Magazine", "Book", "Novel", "Newspaper"], correct: "Book" },
    { word: "Zeitschrift", options: ["Magazine", "Book", "Article", "Newspaper"], correct: "Magazine" },
    { word: "Zeitung", options: ["Book", "Journal", "Magazine", "Newspaper"], correct: "Newspaper" },
    { word: "Computer", options: ["Smartphone", "Tablet", "Laptop", "Computer"], correct: "Computer" },
    { word: "Handy", options: ["Tablet", "Smartphone", "Laptop", "Computer"], correct: "Smartphone" },
    { word: "Laptop", options: ["Tablet", "Computer", "Laptop", "Smartphone"], correct: "Laptop" },
    { word: "Internet", options: ["Network", "System", "Internet", "Connection"], correct: "Internet" },
    { word: "Website", options: ["Page", "Website", "Blog", "Forum"], correct: "Website" },
    { word: "E-Mail", options: ["Message", "Call", "Text", "Email"], correct: "Email" },
    { word: "Telefon", options: ["Phone", "Laptop", "Tablet", "Computer"], correct: "Phone" },
    { word: "Text", options: ["Text", "Message", "Article", "Letter"], correct: "Text" },
    { word: "Nachricht", options: ["News", "Message", "Text", "Call"], correct: "Message" },
    { word: "Foto", options: ["Picture", "Image", "Photo", "Painting"], correct: "Photo" },
    { word: "Video", options: ["Film", "Picture", "Video", "Clip"], correct: "Video" },
    { word: "Filme", options: ["Music", "Movies", "Video", "News"], correct: "Movies" },
    { word: "Musik", options: ["Movies", "Music", "Video", "Sound"], correct: "Music" },
    { word: "Lied", options: ["Song", "Dance", "Music", "Voice"], correct: "Song" },
    { word: "Tanz", options: ["Song", "Dance", "Performance", "Rhythm"], correct: "Dance" },
    { word: "Theater", options: ["Cinema", "Theater", "Concert", "Performance"], correct: "Theater" },
    { word: "Konzerte", options: ["Concert", "Performance", "Show", "Event"], correct: "Concert" },
    { word: "Messe", options: ["Fair", "Exhibition", "Trade", "Event"], correct: "Fair" }
    ],
    B2: [
        { word: "Verantwortung", options: ["Responsibility", "Duty", "Task", "Obligation"], correct: "Responsibility" },
    { word: "Abwechslung", options: ["Variety", "Change", "Difference", "Opportunity"], correct: "Variety" },
    { word: "Aussicht", options: ["View", "Option", "Prospect", "Outlook"], correct: "View" },
    { word: "Fähigkeit", options: ["Ability", "Capability", "Skill", "Talent"], correct: "Ability" },
    { word: "Herausforderung", options: ["Challenge", "Opportunity", "Obstacle", "Problem"], correct: "Challenge" },
    { word: "Zustimmung", options: ["Consent", "Agreement", "Disagreement", "Refusal"], correct: "Consent" },
    { word: "Fortschritt", options: ["Progress", "Development", "Change", "Movement"], correct: "Progress" },
    { word: "Wachstum", options: ["Growth", "Development", "Progress", "Expansion"], correct: "Growth" },
    { word: "Vertrauen", options: ["Trust", "Faith", "Reliability", "Confidence"], correct: "Trust" },
    { word: "Selbstbewusstsein", options: ["Self-awareness", "Confidence", "Pride", "Self-esteem"], correct: "Confidence" },
    { word: "Unterschied", options: ["Difference", "Variation", "Similarity", "Contrast"], correct: "Difference" },
    { word: "Ziel", options: ["Goal", "Aim", "Objective", "Target"], correct: "Goal" },
    { word: "Bedingung", options: ["Condition", "Requirement", "Provision", "Circumstance"], correct: "Condition" },
    { word: "Verhandlung", options: ["Negotiation", "Discussion", "Debate", "Agreement"], correct: "Negotiation" },
    { word: "Abschluss", options: ["Conclusion", "Completion", "Finish", "Result"], correct: "Conclusion" },
    { word: "Wirkung", options: ["Effect", "Impact", "Result", "Outcome"], correct: "Effect" },
    { word: "Erscheinung", options: ["Appearance", "Phenomenon", "Occurrence", "Sight"], correct: "Appearance" },
    { word: "Zufriedenheit", options: ["Contentment", "Satisfaction", "Happiness", "Fulfillment"], correct: "Satisfaction" },
    { word: "Einfluss", options: ["Influence", "Effect", "Impact", "Control"], correct: "Influence" },
    { word: "Gefühl", options: ["Feeling", "Emotion", "Sense", "Thought"], correct: "Feeling" },
    { word: "Bedeutung", options: ["Meaning", "Importance", "Significance", "Sense"], correct: "Meaning" },
    { word: "Wert", options: ["Value", "Worth", "Cost", "Price"], correct: "Value" },
    { word: "Veränderung", options: ["Change", "Alteration", "Transformation", "Shift"], correct: "Change" },
    { word: "Entwicklung", options: ["Development", "Evolution", "Progress", "Change"], correct: "Development" },
    { word: "Anpassung", options: ["Adjustment", "Adaptation", "Modification", "Change"], correct: "Adjustment" },
    { word: "Gleichgewicht", options: ["Balance", "Equality", "Stability", "Proportion"], correct: "Balance" },
    { word: "Reaktion", options: ["Reaction", "Response", "Reply", "Action"], correct: "Reaction" },
    { word: "Anerkennung", options: ["Recognition", "Appreciation", "Acknowledgment", "Respect"], correct: "Recognition" },
    { word: "Bestätigung", options: ["Confirmation", "Approval", "Affirmation", "Verification"], correct: "Confirmation" },
    { word: "Erfolg", options: ["Success", "Achievement", "Victory", "Win"], correct: "Success" },
    { word: "Misserfolg", options: ["Failure", "Defeat", "Loss", "Mistake"], correct: "Failure" },
    { word: "Verhältnis", options: ["Relationship", "Ratio", "Proportion", "Link"], correct: "Relationship" },
    { word: "Zweck", options: ["Purpose", "Objective", "Goal", "Use"], correct: "Purpose" },
    { word: "Möglichkeit", options: ["Possibility", "Opportunity", "Chance", "Option"], correct: "Possibility" },
    { word: "Einschränkung", options: ["Restriction", "Limitation", "Constrain", "Limitation"], correct: "Restriction" },
    { word: "Neugier", options: ["Curiosity", "Interest", "Wonder", "Desire"], correct: "Curiosity" },
    { word: "Besonderheit", options: ["Specialty", "Particularity", "Uniqueness", "Feature"], correct: "Specialty" },
    { word: "Entscheidung", options: ["Decision", "Choice", "Option", "Judgment"], correct: "Decision" },
    { word: "Wahrheit", options: ["Truth", "Fact", "Reality", "Accuracy"], correct: "Truth" },
    { word: "Lüge", options: ["Lie", "Truth", "Fact", "Statement"], correct: "Lie" },
    { word: "Zielgruppe", options: ["Audience", "Target group", "Market", "Group"], correct: "Target group" },
    { word: "Umgang", options: ["Treatment", "Handling", "Interaction", "Communication"], correct: "Interaction" },
    { word: "Störung", options: ["Disruption", "Disturbance", "Interruption", "Problem"], correct: "Disruption" },
    { word: "Bedeutung", options: ["Meaning", "Importance", "Value", "Significance"], correct: "Meaning" },
    { word: "Betrieb", options: ["Operation", "Business", "Factory", "Company"], correct: "Business" },
    { word: "Wirtschaft", options: ["Economy", "Business", "Industry", "Trade"], correct: "Economy" },
    { word: "Verhalten", options: ["Behavior", "Conduct", "Action", "Reaction"], correct: "Behavior" },
    { word: "Aufgabe", options: ["Task", "Assignment", "Mission", "Duty"], correct: "Task" },
    { word: "Abteilung", options: ["Department", "Section", "Division", "Unit"], correct: "Department" },
    { word: "Forschung", options: ["Research", "Study", "Experiment", "Analysis"], correct: "Research" },
    { word: "Verwendung", options: ["Usage", "Use", "Application", "Function"], correct: "Use" },
    { word: "Erklärung", options: ["Explanation", "Definition", "Clarification", "Statement"], correct: "Explanation" },
    { word: "Untersuchung", options: ["Investigation", "Examination", "Analysis", "Survey"], correct: "Investigation" },
    { word: "Voraussetzung", options: ["Requirement", "Condition", "Prerequisite", "Need"], correct: "Requirement" },
    { word: "Vereinbarung", options: ["Agreement", "Contract", "Deal", "Understanding"], correct: "Agreement" },
    { word: "Kondition", options: ["Condition", "State", "State of mind", "Situation"], correct: "Condition" },
    { word: "Begriff", options: ["Term", "Concept", "Idea", "Word"], correct: "Term" },
    { word: "Aussage", options: ["Statement", "Claim", "Argument", "Fact"], correct: "Statement" },
    { word: "Verwendung", options: ["Usage", "Application", "Use", "Function"], correct: "Usage" },
    { word: "Erlaubnis", options: ["Permission", "License", "Approval", "Consent"], correct: "Permission" },
    { word: "Überzeugung", options: ["Conviction", "Belief", "Opinion", "View"], correct: "Conviction" },
    { word: "Mangel", options: ["Deficit", "Lack", "Shortage", "Absence"], correct: "Lack" },
    { word: "Vorbereitung", options: ["Preparation", "Plan", "Arrangement", "Readiness"], correct: "Preparation" },
    { word: "Beteiligung", options: ["Participation", "Involvement", "Contribution", "Engagement"], correct: "Participation" },
    { word: "Aussicht", options: ["View", "Outlook", "Perspective", "Prospect"], correct: "View" },
    { word: "Verhalten", options: ["Behavior", "Conduct", "Performance", "Action"], correct: "Behavior" },
    { word: "Voraussetzung", options: ["Prerequisite", "Condition", "Requirement", "Need"], correct: "Prerequisite" },
    { word: "Geschenk", options: ["Gift", "Present", "Offer", "Reward"], correct: "Gift" },
    { word: "Erklärung", options: ["Explanation", "Clarification", "Statement", "Reason"], correct: "Explanation" },
    { word: "Gegenteil", options: ["Opposite", "Contradiction", "Counterpart", "Reverse"], correct: "Opposite" },
    { word: "Ergebnis", options: ["Result", "Outcome", "Conclusion", "Effect"], correct: "Result" },
    { word: "Zustimmung", options: ["Consent", "Approval", "Agreement", "Acknowledgment"], correct: "Consent" },
    { word: "Kritik", options: ["Criticism", "Review", "Feedback", "Analysis"], correct: "Criticism" },
    { word: "Vermögen", options: ["Wealth", "Asset", "Fortune", "Property"], correct: "Wealth" },
    { word: "Erfolg", options: ["Success", "Achievement", "Victory", "Win"], correct: "Success" },
    { word: "Verhältnis", options: ["Relationship", "Proportion", "Ratio", "Connection"], correct: "Relationship" },
    { word: "Betrieb", options: ["Company", "Business", "Operation", "Firm"], correct: "Business" },
    { word: "Zweck", options: ["Purpose", "Aim", "Objective", "Goal"], correct: "Purpose" },
    { word: "Unterschied", options: ["Difference", "Distinction", "Variation", "Divergence"], correct: "Difference" },
    { word: "Verhandlung", options: ["Negotiation", "Deal", "Discussion", "Bargaining"], correct: "Negotiation" },
    { word: "Beteiligung", options: ["Involvement", "Participation", "Contribution", "Share"], correct: "Involvement" },
    { word: "Überraschung", options: ["Surprise", "Astonishment", "Wonder", "Shock"], correct: "Surprise" },
    { word: "Sicherheit", options: ["Safety", "Security", "Protection", "Assurance"], correct: "Safety" },
    { word: "Lösung", options: ["Solution", "Answer", "Resolution", "Fix"], correct: "Solution" },
    { word: "Kompromiss", options: ["Compromise", "Agreement", "Deal", "Settlement"], correct: "Compromise" },
    { word: "Beitrag", options: ["Contribution", "Input", "Share", "Offer"], correct: "Contribution" },
    { word: "Erwartung", options: ["Expectation", "Anticipation", "Hope", "Assumption"], correct: "Expectation" },
    { word: "Schwierigkeit", options: ["Difficulty", "Challenge", "Obstacle", "Problem"], correct: "Difficulty" },
    { word: "Voraussetzung", options: ["Condition", "Prerequisite", "Requirement", "Necessity"], correct: "Condition" },
    { word: "Verhalten", options: ["Behavior", "Conduct", "Performance", "Reaction"], correct: "Behavior" },
    { word: "Leben", options: ["Life", "Existence", "Living", "Being"], correct: "Life" },
    { word: "Chance", options: ["Chance", "Opportunity", "Possibility", "Shot"], correct: "Chance" },
    { word: "Erfahrung", options: ["Experience", "Knowledge", "Skill", "Understanding"], correct: "Experience" },
    { word: "Entscheidung", options: ["Decision", "Choice", "Judgment", "Verdict"], correct: "Decision" },
    { word: "Angabe", options: ["Statement", "Indication", "Detail", "Information"], correct: "Statement" },
    { word: "Gleichgewicht", options: ["Balance", "Stability", "Equality", "Equilibrium"], correct: "Balance" },
    { word: "Konkurrenz", options: ["Competition", "Rivalry", "Opposition", "Contest"], correct: "Competition" },
    { word: "Anforderung", options: ["Requirement", "Demand", "Condition", "Request"], correct: "Requirement" },
    { word: "Verlust", options: ["Loss", "Defeat", "Drop", "Failure"], correct: "Loss" },
    { word: "Zufriedenheit", options: ["Satisfaction", "Contentment", "Happiness", "Fulfillment"], correct: "Satisfaction" },
    { word: "Ergebnis", options: ["Outcome", "Result", "Conclusion", "Effect"], correct: "Outcome" },
    { word: "Abstimmung", options: ["Vote", "Poll", "Agreement", "Survey"], correct: "Vote" },
    { word: "Ansicht", options: ["View", "Opinion", "Perspective", "Attitude"], correct: "View" },
    { word: "Vertrauen", options: ["Trust", "Reliance", "Faith", "Confidence"], correct: "Trust" },
    { word: "Unabhängigkeit", options: ["Independence", "Freedom", "Autonomy", "Sovereignty"], correct: "Independence" },
    { word: "Anerkennung", options: ["Recognition", "Acknowledgment", "Appreciation", "Validation"], correct: "Recognition" },
    { word: "Überzeugung", options: ["Belief", "Conviction", "View", "Idea"], correct: "Belief" },
    { word: "Verbindung", options: ["Connection", "Link", "Relation", "Bond"], correct: "Connection" },
    { word: "Ablauf", options: ["Process", "Procedure", "Flow", "Course"], correct: "Process" },
    { word: "Kombination", options: ["Combination", "Blend", "Mixture", "Union"], correct: "Combination" }
    ],
    C1: [
        { word: "Herausforderung", options: ["Challenge", "Obligation", "Task", "Mission"], correct: "Challenge" },
    { word: "Verantwortung", options: ["Responsibility", "Duty", "Task", "Obligation"], correct: "Responsibility" },
    { word: "Zusammenhang", options: ["Context", "Connection", "Relation", "Link"], correct: "Context" },
    { word: "Komplexität", options: ["Complexity", "Difficulty", "Challenge", "Intricacy"], correct: "Complexity" },
    { word: "Verständnis", options: ["Understanding", "Insight", "Comprehension", "Knowledge"], correct: "Understanding" },
    { word: "Erkenntnis", options: ["Insight", "Understanding", "Realization", "Knowledge"], correct: "Insight" },
    { word: "Entwicklung", options: ["Development", "Growth", "Evolution", "Progress"], correct: "Development" },
    { word: "Bedeutung", options: ["Meaning", "Importance", "Significance", "Value"], correct: "Meaning" },
    { word: "Wirkung", options: ["Effect", "Impact", "Result", "Outcome"], correct: "Effect" },
    { word: "Fähigkeit", options: ["Ability", "Skill", "Capability", "Competence"], correct: "Ability" },
    { word: "Verhalten", options: ["Behavior", "Conduct", "Action", "Manner"], correct: "Behavior" },
    { word: "Verhandlung", options: ["Negotiation", "Discussion", "Deal", "Agreement"], correct: "Negotiation" },
    { word: "Möglichkeiten", options: ["Possibilities", "Opportunities", "Options", "Chances"], correct: "Possibilities" },
    { word: "Einsicht", options: ["Insight", "Understanding", "Viewpoint", "Perspective"], correct: "Insight" },
    { word: "Zukunft", options: ["Future", "Destiny", "Prospect", "Time ahead"], correct: "Future" },
    { word: "Kompetenz", options: ["Competence", "Ability", "Skill", "Qualification"], correct: "Competence" },
    { word: "Verständlichkeit", options: ["Clarity", "Understandability", "Simplicity", "Accessibility"], correct: "Clarity" },
    { word: "Schwierigkeit", options: ["Difficulty", "Complication", "Problem", "Challenge"], correct: "Difficulty" },
    { word: "Bedingung", options: ["Condition", "Requirement", "Clause", "Term"], correct: "Condition" },
    { word: "Sichtweise", options: ["Point of view", "Opinion", "Outlook", "Perspective"], correct: "Point of view" },
    { word: "Anforderungen", options: ["Requirements", "Demands", "Conditions", "Expectations"], correct: "Requirements" },
    { word: "Erfahrung", options: ["Experience", "Knowledge", "Skill", "Competence"], correct: "Experience" },
    { word: "Hintergrund", options: ["Background", "Context", "Foundation", "Cause"], correct: "Background" },
    { word: "Prozess", options: ["Process", "Procedure", "System", "Method"], correct: "Process" },
    { word: "Zustimmung", options: ["Consent", "Approval", "Agreement", "Confirmation"], correct: "Consent" },
    { word: "Hoffnung", options: ["Hope", "Aspiration", "Expectation", "Desire"], correct: "Hope" },
    { word: "Kritik", options: ["Criticism", "Review", "Evaluation", "Feedback"], correct: "Criticism" },
    { word: "Beteiligung", options: ["Participation", "Involvement", "Contribution", "Share"], correct: "Participation" },
    { word: "Entscheidung", options: ["Decision", "Choice", "Judgment", "Verdict"], correct: "Decision" },
    { word: "Erklärung", options: ["Explanation", "Statement", "Clarification", "Definition"], correct: "Explanation" },
    { word: "Möglichkeit", options: ["Possibility", "Opportunity", "Chance", "Option"], correct: "Possibility" },
    { word: "Bestätigung", options: ["Confirmation", "Validation", "Approval", "Affirmation"], correct: "Confirmation" },
    { word: "Zufriedenheit", options: ["Satisfaction", "Contentment", "Fulfillment", "Pleasure"], correct: "Satisfaction" },
    { word: "Nachhaltigkeit", options: ["Sustainability", "Endurance", "Longevity", "Viability"], correct: "Sustainability" },
    { word: "Ziel", options: ["Goal", "Target", "Aim", "Objective"], correct: "Goal" },
    { word: "Verbindung", options: ["Connection", "Link", "Relation", "Bond"], correct: "Connection" },
    { word: "Kombination", options: ["Combination", "Mix", "Union", "Blend"], correct: "Combination" },
    { word: "Ergebnis", options: ["Result", "Outcome", "Conclusion", "Effect"], correct: "Result" },
    { word: "Fortschritt", options: ["Progress", "Advancement", "Development", "Improvement"], correct: "Progress" },
    { word: "Schlussfolgerung", options: ["Conclusion", "Inference", "Deduction", "Result"], correct: "Conclusion" },
    { word: "Mangel", options: ["Lack", "Deficit", "Shortage", "Absence"], correct: "Lack" },
    { word: "Aussicht", options: ["View", "Prospect", "Outlook", "Perspective"], correct: "View" },
    { word: "Voraussetzung", options: ["Prerequisite", "Condition", "Requirement", "Term"], correct: "Prerequisite" },
    { word: "Vertrauen", options: ["Trust", "Confidence", "Reliance", "Belief"], correct: "Trust" },
    { word: "Entwicklung", options: ["Development", "Growth", "Evolution", "Progress"], correct: "Development" },
    { word: "Sicherheit", options: ["Safety", "Security", "Protection", "Certainty"], correct: "Safety" },
    { word: "Einfluss", options: ["Influence", "Impact", "Effect", "Power"], correct: "Influence" },
    { word: "Erfüllung", options: ["Fulfillment", "Satisfaction", "Completion", "Achievement"], correct: "Fulfillment" },
    { word: "Verzögerung", options: ["Delay", "Postponement", "Interruption", "Deferral"], correct: "Delay" },
    { word: "Vorbereitung", options: ["Preparation", "Readiness", "Setup", "Planning"], correct: "Preparation" },
    { word: "Widerstand", options: ["Resistance", "Opposition", "Defiance", "Resilience"], correct: "Resistance" },
    { word: "Abstimmung", options: ["Voting", "Poll", "Agreement", "Approval"], correct: "Voting" },
    { word: "Bewertung", options: ["Evaluation", "Assessment", "Rating", "Review"], correct: "Evaluation" },
    { word: "Verkehr", options: ["Traffic", "Transport", "Movement", "Flow"], correct: "Traffic" },
    { word: "Ausdruck", options: ["Expression", "Gesture", "Symbol", "Phrase"], correct: "Expression" },
    { word: "Schwierigkeit", options: ["Difficulty", "Problem", "Challenge", "Obstacle"], correct: "Difficulty" },
    { word: "Gegenteil", options: ["Opposite", "Contradiction", "Alternative", "Contrast"], correct: "Opposite" },
    { word: "Einschränkung", options: ["Limitation", "Restriction", "Constraint", "Limitation"], correct: "Limitation" },
    { word: "Erfolg", options: ["Success", "Achievement", "Victory", "Accomplishment"], correct: "Success" },
    { word: "Beziehung", options: ["Relationship", "Connection", "Bond", "Partnership"], correct: "Relationship" },
    { word: "Verfahren", options: ["Method", "Process", "Procedure", "Approach"], correct: "Method" },
    { word: "Dauer", options: ["Duration", "Length", "Period", "Timeframe"], correct: "Duration" },
    { word: "Konsistenz", options: ["Consistency", "Coherence", "Stability", "Uniformity"], correct: "Consistency" },
    { word: "Herausforderung", options: ["Challenge", "Task", "Problem", "Obstacle"], correct: "Challenge" },
    { word: "Verhältnis", options: ["Ratio", "Relationship", "Proportion", "Connection"], correct: "Ratio" },
    { word: "Fähigkeit", options: ["Ability", "Capacity", "Skill", "Talent"], correct: "Ability" },
    { word: "Forschung", options: ["Research", "Study", "Investigation", "Analysis"], correct: "Research" },
    { word: "Verletzung", options: ["Injury", "Harm", "Wound", "Damage"], correct: "Injury" },
    { word: "Wirkung", options: ["Effect", "Impact", "Result", "Consequence"], correct: "Effect" },
    { word: "Erklärung", options: ["Explanation", "Clarification", "Interpretation", "Statement"], correct: "Explanation" },
    { word: "Bedeutung", options: ["Meaning", "Significance", "Value", "Importance"], correct: "Meaning" },
    { word: "Überraschung", options: ["Surprise", "Astonishment", "Shock", "Stunning"], correct: "Surprise" },
    { word: "Entscheidung", options: ["Decision", "Choice", "Judgment", "Verdict"], correct: "Decision" },
    { word: "Bedingung", options: ["Condition", "Requirement", "Term", "Clause"], correct: "Condition" },
    { word: "Gesellschaft", options: ["Society", "Community", "Company", "Organization"], correct: "Society" },
    { word: "Möglichkeit", options: ["Possibility", "Option", "Opportunity", "Chance"], correct: "Possibility" },
    { word: "Verantwortung", options: ["Responsibility", "Duty", "Accountability", "Obligation"], correct: "Responsibility" },
    { word: "Verhandlung", options: ["Negotiation", "Discussion", "Bargaining", "Debate"], correct: "Negotiation" },
    { word: "Erwartung", options: ["Expectation", "Anticipation", "Hope", "Desire"], correct: "Expectation" },
    { word: "Zufriedenheit", options: ["Satisfaction", "Contentment", "Pleasure", "Happiness"], correct: "Satisfaction" },
    { word: "Zustimmung", options: ["Consent", "Approval", "Agreement", "Permission"], correct: "Consent" },
    { word: "Verbindung", options: ["Connection", "Relation", "Link", "Association"], correct: "Connection" },
    { word: "Entwicklung", options: ["Development", "Growth", "Advancement", "Evolution"], correct: "Development" },
    { word: "Lösung", options: ["Solution", "Answer", "Fix", "Resolution"], correct: "Solution" },
    { word: "Wissen", options: ["Knowledge", "Understanding", "Awareness", "Insight"], correct: "Knowledge" },
    { word: "Erfahrung", options: ["Experience", "Practice", "Knowledge", "Expertise"], correct: "Experience" },
    { word: "Voraussetzung", options: ["Prerequisite", "Condition", "Requirement", "Term"], correct: "Prerequisite" },
    { word: "Enttäuschung", options: ["Disappointment", "Frustration", "Sadness", "Defeat"], correct: "Disappointment" },
    { word: "Abstimmung", options: ["Vote", "Poll", "Approval", "Agreement"], correct: "Vote" },
    { word: "Bedingung", options: ["Condition", "Requirement", "Circumstance", "Provision"], correct: "Condition" },
    { word: "Bestätigung", options: ["Confirmation", "Validation", "Affirmation", "Acknowledgment"], correct: "Confirmation" },
    { word: "Überlegung", options: ["Consideration", "Thought", "Deliberation", "Contemplation"], correct: "Consideration" },
    { word: "Kritik", options: ["Criticism", "Review", "Feedback", "Judgment"], correct: "Criticism" },
    { word: "Mangel", options: ["Lack", "Deficiency", "Shortage", "Absence"], correct: "Lack" },
    { word: "Ziel", options: ["Goal", "Aim", "Objective", "Target"], correct: "Goal" },
    { word: "Zukunft", options: ["Future", "Prospect", "Coming", "Time ahead"], correct: "Future" },
    { word: "Hoffnung", options: ["Hope", "Aspiration", "Dream", "Expectation"], correct: "Hope" },
    { word: "Schlussfolgerung", options: ["Conclusion", "Inference", "Deduction", "Result"], correct: "Conclusion" },
    { word: "Toleranz", options: ["Tolerance", "Patience", "Acceptance", "Endurance"], correct: "Tolerance" },
    { word: "Vertrauen", options: ["Trust", "Reliance", "Confidence", "Assurance"], correct: "Trust" },
    { word: "Verschiedenheit", options: ["Diversity", "Difference", "Variety", "Contradiction"], correct: "Diversity" },
    { word: "Geschenk", options: ["Gift", "Present", "Offer", "Surprise"], correct: "Gift" },
    { word: "Verkehr", options: ["Traffic", "Transportation", "Movement", "Flow"], correct: "Traffic" },
    { word: "Hintergrund", options: ["Background", "Context", "Foundation", "Origin"], correct: "Background" }
    ],
    C2: [
        { word: "Erklärung", options: ["Explanation", "Definition", "Description", "Clarification"], correct: "Explanation" },
    { word: "Voraussetzung", options: ["Prerequisite", "Condition", "Requirement", "Obligation"], correct: "Prerequisite" },
    { word: "Komplexität", options: ["Complexity", "Difficulty", "Sophistication", "Intricacy"], correct: "Complexity" },
    { word: "Unterschied", options: ["Difference", "Distinction", "Disparity", "Contrast"], correct: "Difference" },
    { word: "Abstraktion", options: ["Abstraction", "Concept", "Theory", "Idea"], correct: "Abstraction" },
    { word: "Begriff", options: ["Concept", "Term", "Idea", "Word"], correct: "Concept" },
    { word: "Erkenntnis", options: ["Insight", "Realization", "Understanding", "Awareness"], correct: "Insight" },
    { word: "Verwirklichung", options: ["Realization", "Implementation", "Execution", "Fulfillment"], correct: "Realization" },
    { word: "Bedeutung", options: ["Meaning", "Significance", "Value", "Importance"], correct: "Meaning" },
    { word: "Verbindung", options: ["Connection", "Link", "Relation", "Association"], correct: "Connection" },
    { word: "Einsicht", options: ["Insight", "View", "Understanding", "Perspective"], correct: "Insight" },
    { word: "Störung", options: ["Disturbance", "Disruption", "Interruption", "Interference"], correct: "Disturbance" },
    { word: "Zufriedenheit", options: ["Satisfaction", "Contentment", "Happiness", "Pleasure"], correct: "Satisfaction" },
    { word: "Überlegung", options: ["Consideration", "Reflection", "Contemplation", "Thought"], correct: "Consideration" },
    { word: "Verantwortung", options: ["Responsibility", "Accountability", "Duty", "Obligation"], correct: "Responsibility" },
    { word: "Gefühl", options: ["Feeling", "Emotion", "Sensation", "Sentiment"], correct: "Feeling" },
    { word: "Anerkennung", options: ["Recognition", "Acknowledgment", "Appreciation", "Validation"], correct: "Recognition" },
    { word: "Aussage", options: ["Statement", "Declaration", "Assertion", "Claim"], correct: "Statement" },
    { word: "Unabhängigkeit", options: ["Independence", "Autonomy", "Freedom", "Self-sufficiency"], correct: "Independence" },
    { word: "Wechselwirkung", options: ["Interaction", "Reciprocity", "Impact", "Interplay"], correct: "Interaction" },
    { word: "Zweck", options: ["Purpose", "Goal", "Objective", "Aim"], correct: "Purpose" },
    { word: "Verurteilung", options: ["Condemnation", "Judgment", "Conviction", "Censure"], correct: "Condemnation" },
    { word: "Eignung", options: ["Suitability", "Fitness", "Adequacy", "Capability"], correct: "Suitability" },
    { word: "Selbstbestimmung", options: ["Self-determination", "Autonomy", "Independence", "Freedom"], correct: "Self-determination" },
    { word: "Erschöpfung", options: ["Exhaustion", "Fatigue", "Tiredness", "Weariness"], correct: "Exhaustion" },
    { word: "Widerspruch", options: ["Contradiction", "Disagreement", "Opposition", "Conflict"], correct: "Contradiction" },
    { word: "Erklärung", options: ["Explanation", "Clarification", "Statement", "Interpretation"], correct: "Explanation" },
    { word: "Darbietung", options: ["Presentation", "Exhibition", "Display", "Performance"], correct: "Presentation" },
    { word: "Zustimmung", options: ["Consent", "Approval", "Agreement", "Permission"], correct: "Consent" },
    { word: "Beziehung", options: ["Relationship", "Connection", "Bond", "Link"], correct: "Relationship" },
    { word: "Konflikt", options: ["Conflict", "Dispute", "Clash", "Disagreement"], correct: "Conflict" },
    { word: "Abgrenzung", options: ["Demarcation", "Separation", "Division", "Boundary"], correct: "Demarcation" },
    { word: "Ausdruck", options: ["Expression", "Phrase", "Word", "Gesture"], correct: "Expression" },
    { word: "Veränderung", options: ["Change", "Alteration", "Modification", "Transformation"], correct: "Change" },
    { word: "Anpassung", options: ["Adaptation", "Adjustment", "Modification", "Change"], correct: "Adaptation" },
    { word: "Wirkung", options: ["Effect", "Impact", "Result", "Consequence"], correct: "Effect" },
    { word: "Wahrnehmung", options: ["Perception", "Awareness", "Cognition", "Sensation"], correct: "Perception" },
    { word: "Verlust", options: ["Loss", "Deprivation", "Diminishment", "Deficiency"], correct: "Loss" },
    { word: "Erziehung", options: ["Education", "Upbringing", "Teaching", "Training"], correct: "Education" },
    { word: "Inhalt", options: ["Content", "Substance", "Material", "Essence"], correct: "Content" },
    { word: "Mangel", options: ["Lack", "Deficiency", "Shortage", "Absence"], correct: "Lack" },
    { word: "Unterscheidung", options: ["Distinction", "Difference", "Discrimination", "Separation"], correct: "Distinction" },
    { word: "Fortschritt", options: ["Progress", "Advancement", "Development", "Improvement"], correct: "Progress" },
    { word: "Gegenteil", options: ["Opposite", "Contrary", "Inverse", "Reverse"], correct: "Opposite" },
    { word: "Erneuerung", options: ["Renewal", "Rejuvenation", "Restoration", "Revival"], correct: "Renewal" },
    { word: "Bereitschaft", options: ["Willingness", "Readiness", "Preparedness", "Eagerness"], correct: "Willingness" },
    { word: "Gefährdung", options: ["Hazard", "Endangerment", "Risk", "Threat"], correct: "Hazard" },
    { word: "Auswirkung", options: ["Impact", "Effect", "Consequence", "Result"], correct: "Impact" },
    { word: "Verlangen", options: ["Desire", "Craving", "Longing", "Wish"], correct: "Desire" },
    { word: "Vereinigung", options: ["Union", "Association", "Alliance", "Merger"], correct: "Union" },
    { word: "Herausforderung", options: ["Challenge", "Test", "Trial", "Difficulty"], correct: "Challenge" },
    { word: "Verantwortlichkeit", options: ["Accountability", "Responsibility", "Obligation", "Duty"], correct: "Accountability" },
    { word: "Vertraulichkeit", options: ["Confidentiality", "Secrecy", "Privacy", "Intimacy"], correct: "Confidentiality" },
    { word: "Behauptung", options: ["Claim", "Assertion", "Statement", "Declaration"], correct: "Claim" },
    { word: "Verfeinerung", options: ["Refinement", "Enhancement", "Polishing", "Improvement"], correct: "Refinement" },
    { word: "Begrenzung", options: ["Limitation", "Restriction", "Boundary", "Constraint"], correct: "Limitation" },
    { word: "Kombination", options: ["Combination", "Mixture", "Fusion", "Integration"], correct: "Combination" },{ word: "Überzeugung", options: ["Conviction", "Belief", "Opinion", "Trust"], correct: "Conviction" },
    { word: "Unabhängigkeit", options: ["Independence", "Autonomy", "Freedom", "Sovereignty"], correct: "Independence" },
    { word: "Verschiedenheit", options: ["Diversity", "Difference", "Contradiction", "Variation"], correct: "Diversity" },
    { word: "Selbstgenügsamkeit", options: ["Self-sufficiency", "Independence", "Autonomy", "Self-reliance"], correct: "Self-sufficiency" },
    { word: "Unzulänglichkeit", options: ["Inadequacy", "Insufficiency", "Deficiency", "Shortcoming"], correct: "Inadequacy" },
    { word: "Beweisführung", options: ["Argumentation", "Proof", "Justification", "Defense"], correct: "Argumentation" },
    { word: "Herausforderung", options: ["Challenge", "Test", "Difficulty", "Obstacle"], correct: "Challenge" },
    { word: "Vergangenheit", options: ["Past", "History", "Bygone", "Previous"], correct: "Past" },
    { word: "Zusammenhang", options: ["Context", "Connection", "Link", "Correlation"], correct: "Context" },
    { word: "Bedeutungsschwere", options: ["Gravitas", "Significance", "Weight", "Importance"], correct: "Gravitas" },
    { word: "Gegensatz", options: ["Contrast", "Opposition", "Antithesis", "Contradiction"], correct: "Contrast" },
    { word: "Widerspruch", options: ["Contradiction", "Opposition", "Disagreement", "Dispute"], correct: "Contradiction" },
    { word: "Erreichbarkeit", options: ["Accessibility", "Approachability", "Reachability", "Attainability"], correct: "Accessibility" },
    { word: "Entfaltung", options: ["Unfolding", "Development", "Expansion", "Revelation"], correct: "Unfolding" },
    { word: "Abstraktion", options: ["Abstraction", "Conceptualization", "Theorization", "Simplification"], correct: "Abstraction" },
    { word: "Skepsis", options: ["Skepticism", "Doubt", "Cynicism", "Uncertainty"], correct: "Skepticism" },
    { word: "Einschränkung", options: ["Restriction", "Limitation", "Constraint", "Boundary"], correct: "Restriction" },
    { word: "Verwirklichung", options: ["Realization", "Fulfillment", "Actualization", "Execution"], correct: "Realization" },
    { word: "Voraussetzung", options: ["Prerequisite", "Condition", "Requirement", "Assumption"], correct: "Prerequisite" },
    { word: "Untersuchung", options: ["Investigation", "Research", "Examination", "Study"], correct: "Investigation" },
    { word: "Vernunft", options: ["Reason", "Logic", "Rationality", "Intellect"], correct: "Reason" },
    { word: "Verantwortung", options: ["Responsibility", "Accountability", "Obligation", "Duty"], correct: "Responsibility" },
    { word: "Beziehung", options: ["Relationship", "Connection", "Bond", "Association"], correct: "Relationship" },
    { word: "Zufriedenheit", options: ["Satisfaction", "Contentment", "Happiness", "Pleasure"], correct: "Satisfaction" },
    { word: "Mangel", options: ["Lack", "Deficiency", "Shortage", "Absence"], correct: "Lack" },
    { word: "Verwendung", options: ["Use", "Application", "Utilization", "Purpose"], correct: "Use" },
    { word: "Anerkennung", options: ["Recognition", "Acknowledgment", "Appreciation", "Validation"], correct: "Recognition" },
    { word: "Abwägung", options: ["Weighing", "Consideration", "Assessment", "Evaluation"], correct: "Weighing" },
    { word: "Erklärung", options: ["Explanation", "Clarification", "Statement", "Interpretation"], correct: "Explanation" },
    { word: "Befürwortung", options: ["Support", "Endorsement", "Approval", "Advocacy"], correct: "Support" },
    { word: "Unterscheidung", options: ["Distinction", "Differentiation", "Separation", "Segregation"], correct: "Distinction" },
    { word: "Vertrauen", options: ["Trust", "Reliance", "Confidence", "Assurance"], correct: "Trust" },
    { word: "Komplexität", options: ["Complexity", "Intricacy", "Sophistication", "Convolution"], correct: "Complexity" },
    { word: "Fehlerhaftigkeit", options: ["Faultiness", "Imperfection", "Defectiveness", "Error-proneness"], correct: "Faultiness" },
    { word: "Zusammenstellung", options: ["Compilation", "Assembly", "Consolidation", "Collection"], correct: "Compilation" },
    { word: "Abhängigkeit", options: ["Dependency", "Reliance", "Addiction", "Subjugation"], correct: "Dependency" },
    { word: "Herkunft", options: ["Origin", "Source", "Background", "Ancestry"], correct: "Origin" },
    { word: "Bestätigung", options: ["Confirmation", "Affirmation", "Validation", "Approval"], correct: "Confirmation" },
    { word: "Überwachung", options: ["Monitoring", "Surveillance", "Oversight", "Supervision"], correct: "Monitoring" },
    { word: "Wissenschaft", options: ["Science", "Study", "Research", "Knowledge"], correct: "Science" },
    { word: "Veränderung", options: ["Change", "Alteration", "Modification", "Transformation"], correct: "Change" },
    { word: "Unkenntnis", options: ["Ignorance", "Lack of knowledge", "Unawareness", "Illiteracy"], correct: "Ignorance" },
    { word: "Unvorhersehbarkeit", options: ["Unpredictability", "Uncertainty", "Instability", "Volatility"], correct: "Unpredictability" },
    { word: "Verschwörung", options: ["Conspiracy", "Plot", "Scheme", "Intrigue"], correct: "Conspiracy" }
    ]
};

// German Word of the Day Data
const germanWordList = [
{ "word": "Hund", "meaning": "Dog", "plural": "Hunde", "indefinite": "ein", "definite": "der" },
    { "word": "Buch", "meaning": "Book", "plural": "Bücher", "indefinite": "ein", "definite": "das" },
    { "word": "Katze", "meaning": "Cat", "plural": "Katzen", "indefinite": "eine", "definite": "die" },
    { "word": "Auto", "meaning": "Car", "plural": "Autos", "indefinite": "ein", "definite": "das" },
    { "word": "Haus", "meaning": "House", "plural": "Häuser", "indefinite": "ein", "definite": "das" },
    { "word": "Stuhl", "meaning": "Chair", "plural": "Stühle", "indefinite": "ein", "definite": "der" },
    { "word": "Tisch", "meaning": "Table", "plural": "Tische", "indefinite": "ein", "definite": "der" },
    { "word": "Lampe", "meaning": "Lamp", "plural": "Lampen", "indefinite": "eine", "definite": "die" },
    { "word": "Apfel", "meaning": "Apple", "plural": "Äpfel", "indefinite": "ein", "definite": "der" },
    { "word": "Blume", "meaning": "Flower", "plural": "Blumen", "indefinite": "eine", "definite": "die" },
    { "word": "Baum", "meaning": "Tree", "plural": "Bäume", "indefinite": "ein", "definite": "der" },
    { "word": "Koffer", "meaning": "Suitcase", "plural": "Koffer", "indefinite": "ein", "definite": "der" },
    { "word": "Schuh", "meaning": "Shoe", "plural": "Schuhe", "indefinite": "ein", "definite": "der" },
    { "word": "Jacke", "meaning": "Jacket", "plural": "Jacken", "indefinite": "eine", "definite": "die" },
    { "word": "Fenster", "meaning": "Window", "plural": "Fenster", "indefinite": "ein", "definite": "das" },
    { "word": "Bleistift", "meaning": "Pencil", "plural": "Bleistifte", "indefinite": "ein", "definite": "der" },
    { "word": "Heft", "meaning": "Notebook", "plural": "Hefte", "indefinite": "ein", "definite": "das" },
    { "word": "Brille", "meaning": "Glasses", "plural": "Brillen", "indefinite": "eine", "definite": "die" },
    { "word": "Zug", "meaning": "Train", "plural": "Züge", "indefinite": "ein", "definite": "der" },
    { "word": "Küche", "meaning": "Kitchen", "plural": "Küchen", "indefinite": "eine", "definite": "die" },{ "word": "Fahrrad", "meaning": "Bicycle", "plural": "Fahrräder", "indefinite": "ein", "definite": "das" },
    { "word": "Tasche", "meaning": "Bag", "plural": "Taschen", "indefinite": "eine", "definite": "die" },
    { "word": "Uhr", "meaning": "Clock", "plural": "Uhren", "indefinite": "eine", "definite": "die" },
    { "word": "Brot", "meaning": "Bread", "plural": "Brote", "indefinite": "ein", "definite": "das" },
    { "word": "Wasser", "meaning": "Water", "plural": "—", "indefinite": "ein", "definite": "das" },
    { "word": "Messer", "meaning": "Knife", "plural": "Messer", "indefinite": "ein", "definite": "das" },
    { "word": "Gabel", "meaning": "Fork", "plural": "Gabeln", "indefinite": "eine", "definite": "die" },
    { "word": "Löffel", "meaning": "Spoon", "plural": "Löffel", "indefinite": "ein", "definite": "der" },
    { "word": "Stadt", "meaning": "City", "plural": "Städte", "indefinite": "eine", "definite": "die" },
    { "word": "Dorf", "meaning": "Village", "plural": "Dörfer", "indefinite": "ein", "definite": "das" },
    { "word": "Schule", "meaning": "School", "plural": "Schulen", "indefinite": "eine", "definite": "die" },
    { "word": "Flugzeug", "meaning": "Airplane", "plural": "Flugzeuge", "indefinite": "ein", "definite": "das" },
    { "word": "Handy", "meaning": "Mobile Phone", "plural": "Handys", "indefinite": "ein", "definite": "das" },
    { "word": "Computer", "meaning": "Computer", "plural": "Computer", "indefinite": "ein", "definite": "der" },
    { "word": "Kind", "meaning": "Child", "plural": "Kinder", "indefinite": "ein", "definite": "das" },
    { "word": "Lehrer", "meaning": "Teacher (Male)", "plural": "Lehrer", "indefinite": "ein", "definite": "der" },
    { "word": "Lehrerin", "meaning": "Teacher (Female)", "plural": "Lehrerinnen", "indefinite": "eine", "definite": "die" },
    { "word": "Freund", "meaning": "Friend (Male)", "plural": "Freunde", "indefinite": "ein", "definite": "der" },
    { "word": "Freundin", "meaning": "Friend (Female)", "plural": "Freundinnen", "indefinite": "eine", "definite": "die" },
    { "word": "Familie", "meaning": "Family", "plural": "Familien", "indefinite": "eine", "definite": "die" },
    { "word": "Mensch", "meaning": "Person", "plural": "Menschen", "indefinite": "ein", "definite": "der" },
    { "word": "Wald", "meaning": "Forest", "plural": "Wälder", "indefinite": "ein", "definite": "der" },
    { "word": "Berg", "meaning": "Mountain", "plural": "Berge", "indefinite": "ein", "definite": "der" },
    { "word": "See", "meaning": "Lake", "plural": "Seen", "indefinite": "ein", "definite": "der" },
    { "word": "Fluss", "meaning": "River", "plural": "Flüsse", "indefinite": "ein", "definite": "der" },
    { "word": "Stuhl", "meaning": "Chair", "plural": "Stühle", "indefinite": "ein", "definite": "der" },
    { "word": "Hemd", "meaning": "Shirt", "plural": "Hemde", "indefinite": "ein", "definite": "das" },
    { "word": "Hose", "meaning": "Pants", "plural": "Hosen", "indefinite": "eine", "definite": "die" },
    { "word": "Kleid", "meaning": "Dress", "plural": "Kleider", "indefinite": "ein", "definite": "das" },
    { "word": "Zahnbürste", "meaning": "Toothbrush", "plural": "Zahnbürsten", "indefinite": "eine", "definite": "die" },
    { "word": "Schlüssel", "meaning": "Key", "plural": "Schlüssel", "indefinite": "ein", "definite": "der" },
    { "word": "Fleisch", "meaning": "Meat", "plural": "Fleisch", "indefinite": "ein", "definite": "das" },
    { "word": "Gemüse", "meaning": "Vegetable", "plural": "Gemüse", "indefinite": "ein", "definite": "das" },
    { "word": "Kaffee", "meaning": "Coffee", "plural": "Kaffees", "indefinite": "ein", "definite": "der" },
    { "word": "Tee", "meaning": "Tea", "plural": "Tees", "indefinite": "ein", "definite": "der" },
    { "word": "Saft", "meaning": "Juice", "plural": "Säfte", "indefinite": "ein", "definite": "der" },
    { "word": "Zucker", "meaning": "Sugar", "plural": "Zucker", "indefinite": "ein", "definite": "der" },
    { "word": "Salz", "meaning": "Salt", "plural": "Salze", "indefinite": "ein", "definite": "das" },
    { "word": "Papier", "meaning": "Paper", "plural": "Papiere", "indefinite": "ein", "definite": "das" },
    { "word": "Fahne", "meaning": "Flag", "plural": "Fahnen", "indefinite": "eine", "definite": "die" },
    { "word": "Brücke", "meaning": "Bridge", "plural": "Brücken", "indefinite": "eine", "definite": "die" },
    { "word": "Straße", "meaning": "Street", "plural": "Straßen", "indefinite": "eine", "definite": "die" },
    { "word": "Platz", "meaning": "Square", "plural": "Plätze", "indefinite": "ein", "definite": "der" },
    { "word": "Markt", "meaning": "Market", "plural": "Märkte", "indefinite": "ein", "definite": "der" },
    { "word": "Laden", "meaning": "Shop", "plural": "Läden", "indefinite": "ein", "definite": "der" },
    { "word": "Wohnung", "meaning": "Apartment", "plural": "Wohnungen", "indefinite": "eine", "definite": "die" },
    { "word": "Zimmer", "meaning": "Room", "plural": "Zimmer", "indefinite": "ein", "definite": "das" },
    { "word": "Tür", "meaning": "Door", "plural": "Türen", "indefinite": "eine", "definite": "die" },
    { "word": "Torte", "meaning": "Cake", "plural": "Torten", "indefinite": "eine", "definite": "die" },
    { "word": "Pflanze", "meaning": "Plant", "plural": "Pflanzen", "indefinite": "eine", "definite": "die" },
    { "word": "Schiff", "meaning": "Ship", "plural": "Schiffe", "indefinite": "ein", "definite": "das" },
    { "word": "Korb", "meaning": "Basket", "plural": "Körbe", "indefinite": "ein", "definite": "der" },
    { "word": "Löffel", "meaning": "Spoon", "plural": "Löffel", "indefinite": "ein", "definite": "der" },
    { "word": "Zelt", "meaning": "Tent", "plural": "Zelte", "indefinite": "ein", "definite": "das" },
    { "word": "Mütze", "meaning": "Cap", "plural": "Mützen", "indefinite": "eine", "definite": "die" },
    { "word": "Ball", "meaning": "Ball", "plural": "Bälle", "indefinite": "ein", "definite": "der" },
    { "word": "Tasche", "meaning": "Bag", "plural": "Taschen", "indefinite": "eine", "definite": "die" },
    { "word": "Zahnarzt", "meaning": "Dentist (Male)", "plural": "Zahnarzte", "indefinite": "ein", "definite": "der" },
    { "word": "Zahnarzthelferin", "meaning": "Dental Assistant (Female)", "plural": "Zahnarzthelferinnen", "indefinite": "eine", "definite": "die" },
    { "word": "Bauernhof", "meaning": "Farm", "plural": "Bauernhöfe", "indefinite": "ein", "definite": "der" },
    { "word": "Eis", "meaning": "Ice Cream", "plural": "Eis", "indefinite": "ein", "definite": "das" },
    { "word": "Koch", "meaning": "Cook (Male)", "plural": "Köche", "indefinite": "ein", "definite": "der" },
    { "word": "Köchin", "meaning": "Cook (Female)", "plural": "Köchinnen", "indefinite": "eine", "definite": "die" },
    { "word": "Licht", "meaning": "Light", "plural": "Lichter", "indefinite": "ein", "definite": "das" },
    { "word": "Fisch", "meaning": "Fish", "plural": "Fische", "indefinite": "ein", "definite": "der" },
    { "word": "Himmel", "meaning": "Sky", "plural": "Himmel", "indefinite": "ein", "definite": "der" },
    { "word": "Hose", "meaning": "Pants", "plural": "Hosen", "indefinite": "eine", "definite": "die" },
    { "word": "Vogel", "meaning": "Bird", "plural": "Vögel", "indefinite": "ein", "definite": "der" },
    { "word": "Bleistift", "meaning": "Pencil", "plural": "Bleistifte", "indefinite": "ein", "definite": "der" },
    { "word": "Rucksack", "meaning": "Backpack", "plural": "Rucksäcke", "indefinite": "ein", "definite": "der" },
    { "word": "Mütze", "meaning": "Hat", "plural": "Mützen", "indefinite": "eine", "definite": "die" },
    { "word": "Schrank", "meaning": "Cabinet", "plural": "Schränke", "indefinite": "ein", "definite": "der" },
    { "word": "Kreis", "meaning": "Circle", "plural": "Kreise", "indefinite": "ein", "definite": "der" },
    { "word": "Fahrradhelm", "meaning": "Bicycle Helmet", "plural": "Fahrradhelme", "indefinite": "ein", "definite": "der" },
    { "word": "Tanz", "meaning": "Dance", "plural": "Tänze", "indefinite": "ein", "definite": "der" },
    { "word": "Radio", "meaning": "Radio", "plural": "Radios", "indefinite": "ein", "definite": "das" },
    { "word": "Zahn", "meaning": "Tooth", "plural": "Zähne", "indefinite": "ein", "definite": "der" },
    { "word": "Schlüssel", "meaning": "Key", "plural": "Schlüssel", "indefinite": "ein", "definite": "der" },
    { "word": "Treppe", "meaning": "Stairs", "plural": "Treppen", "indefinite": "eine", "definite": "die" },
    { "word": "Apotheke", "meaning": "Pharmacy", "plural": "Apotheken", "indefinite": "eine", "definite": "die" },
    { "word": "Wolke", "meaning": "Cloud", "plural": "Wolken", "indefinite": "eine", "definite": "die" },
    { "word": "Schule", "meaning": "School", "plural": "Schulen", "indefinite": "eine", "definite": "die" },
    { "word": "Woche", "meaning": "Week", "plural": "Wochen", "indefinite": "eine", "definite": "die" },
    { "word": "Seife", "meaning": "Soap", "plural": "Seifen", "indefinite": "eine", "definite": "die" },
    { "word": "Stuhl", "meaning": "Chair", "plural": "Stühle", "indefinite": "ein", "definite": "der" },
    { "word": "Küche", "meaning": "Kitchen", "plural": "Küchen", "indefinite": "eine", "definite": "die" },
    { "word": "Schlüsselbund", "meaning": "Keychain", "plural": "Schlüsselbunde", "indefinite": "ein", "definite": "der" },
    { "word": "Löffel", "meaning": "Spoon", "plural": "Löffel", "indefinite": "ein", "definite": "der" },
    { "word": "Herz", "meaning": "Heart", "plural": "Herzen", "indefinite": "ein", "definite": "das" },
    { "word": "Lied", "meaning": "Song", "plural": "Lieder", "indefinite": "ein", "definite": "das" },
    { "word": "Himmel", "meaning": "Sky", "plural": "Himmel", "indefinite": "ein", "definite": "der" },
    { "word": "Apfelbaum", "meaning": "Apple tree", "plural": "Apfelbäume", "indefinite": "ein", "definite": "der" },
    { "word": "Bäckerei", "meaning": "Bakery", "plural": "Bäckereien", "indefinite": "eine", "definite": "die" },
    { "word": "Blatt", "meaning": "Leaf", "plural": "Blätter", "indefinite": "ein", "definite": "das" },
    { "word": "Brücke", "meaning": "Bridge", "plural": "Brücken", "indefinite": "eine", "definite": "die" },
    { "word": "Buchstabe", "meaning": "Letter", "plural": "Buchstaben", "indefinite": "ein", "definite": "der" },
    { "word": "Büro", "meaning": "Office", "plural": "Büros", "indefinite": "ein", "definite": "das" },
    { "word": "Bücherei", "meaning": "Library", "plural": "Büchereien", "indefinite": "eine", "definite": "die" },
    { "word": "Couch", "meaning": "Couch", "plural": "Couches", "indefinite": "eine", "definite": "die" },
    { "word": "Drache", "meaning": "Dragon", "plural": "Drachen", "indefinite": "ein", "definite": "der" },
    { "word": "Eimer", "meaning": "Bucket", "plural": "Eimer", "indefinite": "ein", "definite": "der" },
    { "word": "Erde", "meaning": "Earth", "plural": "Erden", "indefinite": "eine", "definite": "die" },
    { "word": "Fabrik", "meaning": "Factory", "plural": "Fabriken", "indefinite": "eine", "definite": "die" },
    { "word": "Fahne", "meaning": "Flag", "plural": "Fahnen", "indefinite": "eine", "definite": "die" },
    { "word": "Feder", "meaning": "Feather", "plural": "Federn", "indefinite": "eine", "definite": "die" },
    { "word": "Felsen", "meaning": "Rock", "plural": "Felsen", "indefinite": "ein", "definite": "der" },
    { "word": "Fisch", "meaning": "Fish", "plural": "Fische", "indefinite": "ein", "definite": "der" },
    { "word": "Flasche", "meaning": "Bottle", "plural": "Flaschen", "indefinite": "eine", "definite": "die" },
    { "word": "Flughafen", "meaning": "Airport", "plural": "Flughäfen", "indefinite": "ein", "definite": "der" },
    { "word": "Fuß", "meaning": "Foot", "plural": "Füße", "indefinite": "ein", "definite": "der" },
    { "word": "Garten", "meaning": "Garden", "plural": "Gärten", "indefinite": "ein", "definite": "der" },
    { "word": "Giraffe", "meaning": "Giraffe", "plural": "Giraffen", "indefinite": "eine", "definite": "die" },
    { "word": "Glas", "meaning": "Glass", "plural": "Gläser", "indefinite": "ein", "definite": "das" },
    { "word": "Gras", "meaning": "Grass", "plural": "Gräser", "indefinite": "ein", "definite": "das" },
    { "word": "Hahn", "meaning": "Rooster", "plural": "Hähne", "indefinite": "ein", "definite": "der" },
    { "word": "Hase", "meaning": "Hare", "plural": "Hasen", "indefinite": "ein", "definite": "der" },
    { "word": "Himmel", "meaning": "Sky", "plural": "Himmel", "indefinite": "ein", "definite": "der" },
    { "word": "Hose", "meaning": "Pants", "plural": "Hosen", "indefinite": "eine", "definite": "die" },
    { "word": "Hotel", "meaning": "Hotel", "plural": "Hotels", "indefinite": "ein", "definite": "das" },
    { "word": "Hund", "meaning": "Dog", "plural": "Hunde", "indefinite": "ein", "definite": "der" },
    { "word": "Insel", "meaning": "Island", "plural": "Inseln", "indefinite": "eine", "definite": "die" },
    { "word": "Jacke", "meaning": "Jacket", "plural": "Jacken", "indefinite": "eine", "definite": "die" },
    { "word": "Kaffeetasse", "meaning": "Coffee cup", "plural": "Kaffeetassen", "indefinite": "eine", "definite": "die" },
    { "word": "Kamera", "meaning": "Camera", "plural": "Kameras", "indefinite": "eine", "definite": "die" },
    { "word": "Kante", "meaning": "Edge", "plural": "Kanten", "indefinite": "eine", "definite": "die" },
    { "word": "Käse", "meaning": "Cheese", "plural": "Käse", "indefinite": "ein", "definite": "der" },
    { "word": "Keller", "meaning": "Cellar", "plural": "Keller", "indefinite": "ein", "definite": "der" },
    { "word": "Kreis", "meaning": "Circle", "plural": "Kreise", "indefinite": "ein", "definite": "der" },
    { "word": "Krokodil", "meaning": "Crocodile", "plural": "Krokodile", "indefinite": "ein", "definite": "das" },
    { "word": "Laden", "meaning": "Shop", "plural": "Läden", "indefinite": "ein", "definite": "der" },
    { "word": "Lampe", "meaning": "Lamp", "plural": "Lampen", "indefinite": "eine", "definite": "die" },
    { "word": "Löffel", "meaning": "Spoon", "plural": "Löffel", "indefinite": "ein", "definite": "der" },
    { "word": "Magazin", "meaning": "Magazine", "plural": "Magazine", "indefinite": "ein", "definite": "das" },
    { "word": "Mensch", "meaning": "Human", "plural": "Menschen", "indefinite": "ein", "definite": "der" },
    { "word": "Mütze", "meaning": "Hat", "plural": "Mützen", "indefinite": "eine", "definite": "die" },
    { "word": "Nacht", "meaning": "Night", "plural": "Nächte", "indefinite": "eine", "definite": "die" },
    { "word": "Nase", "meaning": "Nose", "plural": "Nasen", "indefinite": "eine", "definite": "die" },
    { "word": "Obst", "meaning": "Fruit", "plural": "—", "indefinite": "ein", "definite": "das" },
    { "word": "Ohr", "meaning": "Ear", "plural": "Ohren", "indefinite": "ein", "definite": "das" },
    { "word": "Papier", "meaning": "Paper", "plural": "Papiere", "indefinite": "ein", "definite": "das" },
    { "word": "Park", "meaning": "Park", "plural": "Parks", "indefinite": "ein", "definite": "der" },
    { "word": "Pflanze", "meaning": "Plant", "plural": "Pflanzen", "indefinite": "eine", "definite": "die" },
    { "word": "Pilz", "meaning": "Mushroom", "plural": "Pilze", "indefinite": "ein", "definite": "der" },
    { "word": "Pizza", "meaning": "Pizza", "plural": "Pizzen", "indefinite": "eine", "definite": "die" },
    { "word": "Raum", "meaning": "Room", "plural": "Räume", "indefinite": "ein", "definite": "der" },
    { "word": "Regen", "meaning": "Rain", "plural": "—", "indefinite": "ein", "definite": "der" },
    { "word": "Reise", "meaning": "Trip", "plural": "Reisen", "indefinite": "eine", "definite": "die" },
    { "word": "Ring", "meaning": "Ring", "plural": "Ringe", "indefinite": "ein", "definite": "der" },
    { "word": "Rucksack", "meaning": "Backpack", "plural": "Rucksäcke", "indefinite": "ein", "definite": "der" },
    { "word": "Sack", "meaning": "Bag", "plural": "Säcke", "indefinite": "ein", "definite": "der" },
    { "word": "Schiff", "meaning": "Ship", "plural": "Schiffe", "indefinite": "ein", "definite": "das" },
    { "word": "Schlange", "meaning": "Snake", "plural": "Schlangen", "indefinite": "eine", "definite": "die" },
    { "word": "Schrank", "meaning": "Cabinet", "plural": "Schränke", "indefinite": "ein", "definite": "der" },
    { "word": "Schuh", "meaning": "Shoe", "plural": "Schuhe", "indefinite": "ein", "definite": "der" },
    { "word": "Schule", "meaning": "School", "plural": "Schulen", "indefinite": "eine", "definite": "die" },
    { "word": "Schwamm", "meaning": "Sponge", "plural": "Schwämme", "indefinite": "ein", "definite": "der" },
    { "word": "Sonne", "meaning": "Sun", "plural": "Sonnen", "indefinite": "eine", "definite": "die" },
    { "word": "Spinne", "meaning": "Spider", "plural": "Spinnen", "indefinite": "eine", "definite": "die" },
    { "word": "Stadt", "meaning": "City", "plural": "Städte", "indefinite": "eine", "definite": "die" },
    { "word": "Stein", "meaning": "Stone", "plural": "Steine", "indefinite": "ein", "definite": "der" },
    { "word": "Stift", "meaning": "Pen", "plural": "Stifte", "indefinite": "ein", "definite": "der" },
    { "word": "Stuhl", "meaning": "Chair", "plural": "Stühle", "indefinite": "ein", "definite": "der" },
    { "word": "Tasche", "meaning": "Bag", "plural": "Taschen", "indefinite": "eine", "definite": "die" },
    { "word": "Tee", "meaning": "Tea", "plural": "Tees", "indefinite": "ein", "definite": "der" },
    { "word": "Telefon", "meaning": "Telephone", "plural": "Telefone", "indefinite": "ein", "definite": "das" },
    { "word": "Tier", "meaning": "Animal", "plural": "Tiere", "indefinite": "ein", "definite": "das" },
    { "word": "Tochter", "meaning": "Daughter", "plural": "Töchter", "indefinite": "eine", "definite": "die" },
    { "word": "Treppe", "meaning": "Staircase", "plural": "Treppen", "indefinite": "eine", "definite": "die" },
    { "word": "Uhr", "meaning": "Clock", "plural": "Uhren", "indefinite": "eine", "definite": "die" },
    { "word": "Vogel", "meaning": "Bird", "plural": "Vögel", "indefinite": "ein", "definite": "der" },
    { "word": "Wasser", "meaning": "Water", "plural": "—", "indefinite": "ein", "definite": "das" },
    { "word": "Woche", "meaning": "Week", "plural": "Wochen", "indefinite": "eine", "definite": "die" },
    { "word": "Zahn", "meaning": "Tooth", "plural": "Zähne", "indefinite": "ein", "definite": "der" },
    { "word": "Zelt", "meaning": "Tent", "plural": "Zelte", "indefinite": "ein", "definite": "das" }
];

module.exports = { germanQuizData, germanWordList };